package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/nathandelacretaz/compound-agent/internal/util"
	"github.com/spf13/cobra"
)

// polishCmdOptions captures all flag values for the polish command.
type polishCmdOptions struct {
	output, model, specFile, metaEpic, reviewers string
	cycles                                       int
	force                                        bool
}

func polishCmd() *cobra.Command {
	var o polishCmdOptions

	cmd := &cobra.Command{
		Use:   "polish",
		Short: "Generate polish loop script (audit fleet + polish architect + inner loop)",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPolish(cmd, &o)
		},
	}

	cmd.Flags().StringVarP(&o.output, "output", "o", "polish-loop.sh", "Output script path")
	cmd.Flags().IntVar(&o.cycles, "cycles", 3, "Number of polish cycles")
	cmd.Flags().StringVar(&o.model, "model", "claude-opus-4-6[1m]", "Claude model to use")
	cmd.Flags().StringVar(&o.specFile, "spec-file", "", "Path to spec file for audit context (required)")
	cmd.Flags().StringVar(&o.metaEpic, "meta-epic", "", "Parent meta-epic ID (required)")
	cmd.Flags().StringVar(&o.reviewers, "reviewers", "claude-sonnet,claude-opus,gemini,codex", "Comma-separated reviewers")
	cmd.Flags().BoolVar(&o.force, "force", false, "Overwrite existing script")
	return cmd
}

func runPolish(cmd *cobra.Command, o *polishCmdOptions) error {
	if o.specFile == "" {
		return fmt.Errorf("--spec-file is required")
	}
	if o.metaEpic == "" {
		return fmt.Errorf("--meta-epic is required")
	}
	if !o.force {
		if _, err := os.Stat(o.output); err == nil {
			return fmt.Errorf("file %s already exists (use --force to overwrite)", o.output)
		}
	}

	reviewerList := strings.Split(o.reviewers, ",")
	if err := validateReviewers(reviewerList); err != nil {
		return err
	}

	script := generatePolishScript(polishGenerateOptions{
		cycles:    o.cycles,
		model:     o.model,
		specFile:  o.specFile,
		metaEpic:  o.metaEpic,
		reviewers: reviewerList,
	})

	if err := os.MkdirAll(filepath.Dir(o.output), 0755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}
	if err := os.WriteFile(o.output, []byte(script), 0755); err != nil {
		return fmt.Errorf("write script: %w", err)
	}

	cmd.Printf("[ok] Generated polish script: %s\n", o.output)
	cmd.Println("Run it with: bash " + o.output)
	return nil
}

// polishGenerateOptions holds all options for generating the polish script.
type polishGenerateOptions struct {
	cycles    int
	model     string
	specFile  string
	metaEpic  string
	reviewers []string
}

func generatePolishScript(opts polishGenerateOptions) string {
	return polishScriptConfig(opts) +
		polishScriptCrashHandler() +
		polishScriptTimeout() +
		polishScriptPrerequisites() +
		polishScriptReviewerDetection() +
		polishScriptAuditPrompt() +
		polishScriptRunAudit() +
		polishScriptSynthesizeReport() +
		polishScriptPolishArchitect() +
		polishScriptInnerLoop() +
		polishScriptMainLoop() +
		polishScriptPostLoop()
}

// polishScriptConfig returns the header and config section.
func polishScriptConfig(opts polishGenerateOptions) string {
	timestamp := time.Now().Format(time.RFC3339)
	escapedModel := util.ShellEscape(opts.model)
	escapedMetaEpic := util.ShellEscape(opts.metaEpic)
	escapedSpecFile := util.ShellEscape(opts.specFile)
	escapedReviewers := util.ShellEscape(strings.Join(opts.reviewers, " "))

	return fmt.Sprintf(`#!/usr/bin/env bash
# Polish Loop - Generated by: ca polish
# Date: %s
# Iterates N cycles of: audit fleet -> polish architect -> inner infinity loop
#
# Usage:
#   ./polish-loop.sh
#   POLISH_DRY_RUN=1 ./polish-loop.sh  # Preview without executing

set -euo pipefail

# Config
CYCLES=%d
MODEL=%s
META_EPIC=%s
SPEC_FILE=%s
CONFIGURED_REVIEWERS=%s
LOG_DIR="agent_logs"
REVIEW_TIMEOUT=${REVIEW_TIMEOUT:-600}

mkdir -p "$LOG_DIR"

# --- Logging ---
log() {
  echo "[$(date '+%%Y-%%m-%%d %%H:%%M:%%S')] [polish] $*" >&2
}

`, timestamp, opts.cycles, escapedModel, escapedMetaEpic,
		escapedSpecFile, escapedReviewers)
}

// polishScriptCrashHandler returns the EXIT trap.
func polishScriptCrashHandler() string {
	return `# --- Crash Handler ---
_polish_cleanup() {
  local exit_code=$?
  if [ $exit_code -ne 0 ]; then
    log "Polish loop crashed with exit code $exit_code at line ${BASH_LINENO[0]:-unknown}"
    echo "{\"status\":\"crashed\",\"exit_code\":$exit_code,\"cycle\":${cycle:-0},\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"line\":\"${BASH_LINENO[0]:-unknown}\"}" > "$LOG_DIR/.polish-status.json"
    exit $exit_code
  fi
}
trap _polish_cleanup EXIT

`
}

// polishScriptTimeout returns the portable_timeout function.
func polishScriptTimeout() string {
	return `# --- Portable Timeout ---
# GNU timeout -> gtimeout (macOS Homebrew) -> shell fallback
portable_timeout() {
  local secs="$1"; shift
  if command -v timeout >/dev/null 2>&1; then
    timeout "$secs" "$@"
  elif command -v gtimeout >/dev/null 2>&1; then
    gtimeout "$secs" "$@"
  else
    "$@" &
    local pid=$!
    ( sleep "$secs" && kill "$pid" 2>/dev/null ) &
    local watchdog=$!
    wait "$pid" 2>/dev/null
    local rc=$?
    kill "$watchdog" 2>/dev/null
    wait "$watchdog" 2>/dev/null
    return $rc
  fi
}

`
}

// polishScriptPrerequisites returns the prerequisite checks.
func polishScriptPrerequisites() string {
	return `# --- Prerequisites ---
command -v claude >/dev/null 2>&1 || { echo "ERROR: claude CLI not found"; exit 1; }
command -v bd >/dev/null 2>&1 || { echo "ERROR: bd CLI not found"; exit 1; }
command -v npx >/dev/null 2>&1 || { echo "ERROR: npx not found (needed for inner loop)"; exit 1; }
[ -f "$SPEC_FILE" ] || { log "ERROR: spec file not found: $SPEC_FILE"; exit 1; }

`
}

// polishScriptReviewerDetection returns the reviewer CLI detection function with health checks.
func polishScriptReviewerDetection() string {
	return `# --- Reviewer Detection ---
detect_polish_reviewers() {
  AVAILABLE_REVIEWERS=""
  for reviewer in $CONFIGURED_REVIEWERS; do
    local cli_name
    case "$reviewer" in
      (claude-sonnet|claude-opus) cli_name="claude" ;;
      (gemini)                    cli_name="gemini" ;;
      (codex)                     cli_name="codex" ;;
      (*) log "WARN: unknown reviewer $reviewer"; continue ;;
    esac
    if ! command -v "$cli_name" >/dev/null 2>&1; then
      log "WARN: $reviewer configured but $cli_name CLI not found -- skipping"
      continue
    fi
    if ! portable_timeout 10 "$cli_name" --version >/dev/null 2>&1; then
      log "WARN: $reviewer configured but $cli_name health check failed -- skipping"
      continue
    fi
    AVAILABLE_REVIEWERS="$AVAILABLE_REVIEWERS $reviewer"
  done
  AVAILABLE_REVIEWERS="${AVAILABLE_REVIEWERS# }"
  if [ -z "$AVAILABLE_REVIEWERS" ]; then
    log "ERROR: no reviewer CLIs available"
    exit 1
  fi
  log "Available reviewers: $AVAILABLE_REVIEWERS"
}

`
}

// polishScriptAuditPrompt returns the build_audit_prompt function.
func polishScriptAuditPrompt() string { //nolint:funlen // bash template string
	return `# --- Audit Prompt (BGT Checklist) ---
build_audit_prompt() {
  local cycle_num="$1"
  local spec_content
  spec_content=$(cat "$SPEC_FILE" 2>/dev/null || echo "(spec file not found)")

  cat <<'AUDIT_PROMPT_EOF'
You are a senior quality auditor performing a holistic review of the entire implementation.

## Your Task
Evaluate the FULL codebase against the Build Great Things pre-ship quality checklist below.
Do NOT focus on recent diffs -- review the entire implementation holistically.
Produce a structured report with P0/P1/P2 findings.

## Build Great Things Pre-Ship Checklist

### States (5 required per data view)
- [ ] loading state -- skeleton or spinner while data fetches
- [ ] empty state -- helpful message and CTA when no data exists
- [ ] error state -- clear error message with recovery action
- [ ] offline state -- graceful degradation when network unavailable
- [ ] partial data state -- sensible rendering with incomplete data

### Interaction
- [ ] hover/active/focus/disabled states defined for all interactive elements
- [ ] focus styles visible and accessible (not just outline: none)
- [ ] press feedback -- visual response within 100ms
- [ ] validation feedback -- inline, immediate, specific
- [ ] page transitions -- smooth, purposeful, not jarring

### Visual Craft
- [ ] 3+ levels of typography hierarchy (size, weight, color)
- [ ] de-emphasis used (not everything can be bold/primary)
- [ ] geometric spacing scale (4/8/16/24/32/48/64) -- no arbitrary values
- [ ] no borders where spacing, background color, or shadow would work
- [ ] consistent elevation/shadow scale
- [ ] semantic color tokens (not raw hex)
- [ ] scroll animations -- choreographed, not just fade-in
- [ ] optimized images -- proper format, sizing, lazy loading
- [ ] consistent icon style and sizing

### Responsiveness
- [ ] mobile is first-class (different IA, content priority, interaction patterns)
- [ ] 44x44px minimum touch targets
- [ ] fluid typography (clamp or viewport units)
- [ ] no horizontal scroll on any breakpoint

### Performance
- [ ] Core Web Vitals: LCP < 2.5s, INP < 200ms, CLS < 0.1
- [ ] font loading strategy (font-display, preload, size-adjust fallbacks)
- [ ] above-fold content renders without JavaScript where possible

### Accessibility
- [ ] semantic HTML elements used (not div soup)
- [ ] ARIA only where semantic HTML insufficient (minimal ARIA)
- [ ] color contrast meets WCAG AA (4.5:1 for text)
- [ ] prefers-reduced-motion respected
- [ ] live region announcements for dynamic content

### Completeness
- [ ] 404 page designed (not default)
- [ ] favicon and Open Graph tags present
- [ ] print styles or print-friendly view

### Common AI Laziness Anti-Patterns
- [ ] NOT shallow component design
- [ ] NOT generic UI -- curated palettes, specific typeface pairings, deliberate whitespace
- [ ] NOT skipping polish phases -- motion and performance phases are mandatory
- [ ] NOT first-design-only -- design it twice before committing
- [ ] NOT missing visual hierarchy
- [ ] NOT edge states only on happy path
- [ ] NOT flat interactions -- every click/hover/scroll needs feedback
- [ ] NOT cookie-cutter layouts
- [ ] NOT borders everywhere -- try spacing, background color, shadows first
- [ ] NOT afterthought mobile
- [ ] NOT ignoring font loading
- [ ] NOT arbitrary spacing -- use geometric scale only

## Output Format
Structure your report as:

### P0 -- Must Fix (blocks quality)
- Finding description with file/line references

### P1 -- Should Fix (significant quality gap)
- Finding description with file/line references

### P2 -- Nice to Fix (polish opportunity)
- Finding description with file/line references

### Summary
- Overall assessment of craft quality (1-2 sentences)
- Top 3 highest-impact improvements

AUDIT_PROMPT_EOF

  echo ""
  echo "## Spec Context"
  echo "$spec_content"
  echo ""
  echo "## Cycle"
  echo "This is polish cycle $cycle_num of $CYCLES."
}

`
}

// polishScriptRunAudit returns the run_polish_audit function with PID tracking and timeouts.
func polishScriptRunAudit() string { //nolint:funlen // bash template string
	return `# --- Spawn Reviewers ---
run_polish_audit() {
  local cycle_num="$1"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"
  mkdir -p "$cycle_dir"

  log "Cycle $cycle_num: building audit prompt"
  local prompt_file="$cycle_dir/audit-prompt.md"
  build_audit_prompt "$cycle_num" > "$prompt_file"

  log "Cycle $cycle_num: spawning reviewers"
  local pids=""
  for reviewer in $AVAILABLE_REVIEWERS; do
    local report="$cycle_dir/$reviewer-report.md"
    local model_name=""

    case "$reviewer" in
      (claude-opus)   model_name="claude-opus-4-6[1m]" ;;
      (claude-sonnet) model_name="claude-sonnet-4-6" ;;
    esac

    if [ "${POLISH_DRY_RUN:-}" = "1" ]; then
      log "DRY RUN: would spawn $reviewer"
      echo "(dry run -- no actual review)" > "$report"
      continue
    fi

    case "$reviewer" in
      (claude-opus|claude-sonnet)
        (portable_timeout "$REVIEW_TIMEOUT" claude --model "$model_name" \
          --dangerously-skip-permissions \
          --permission-mode auto \
          --output-format text \
          -p - < "$prompt_file" > "$report" 2>"$cycle_dir/$reviewer.stderr" || true) &
        ;;
      (gemini)
        (portable_timeout "$REVIEW_TIMEOUT" gemini --yolo \
          < "$prompt_file" \
          > "$report" 2>"$cycle_dir/$reviewer.stderr" || true) &
        ;;
      (codex)
        (portable_timeout "$REVIEW_TIMEOUT" codex exec --full-auto \
          -o "$report" -- - < "$prompt_file" 2>"$cycle_dir/$reviewer.stderr" || true) &
        ;;
    esac
    pids="$pids $!"
    log "Spawned $reviewer (PID $!)"
  done

  log "Waiting for all reviewers to complete"
  for pid in $pids; do wait "$pid" 2>/dev/null || true; done
  log "All reviewers completed for cycle $cycle_num"
}

`
}

// polishScriptSynthesizeReport returns the synthesize_report function.
func polishScriptSynthesizeReport() string {
	return `# --- Synthesize Report ---
synthesize_report() {
  local cycle_num="$1"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"
  local report_file="docs/specs/polish-report-cycle-${cycle_num}.md"

  mkdir -p "$(dirname "$report_file")"

  log "Synthesizing polish report for cycle $cycle_num"

  {
    echo "# Polish Report -- Cycle $cycle_num"
    echo ""
    echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    for reviewer in $AVAILABLE_REVIEWERS; do
      local report="$cycle_dir/$reviewer-report.md"
      if [ -s "$report" ]; then
        echo "## $reviewer"
        echo ""
        cat "$report"
        echo ""
      else
        echo "## $reviewer"
        echo ""
        echo "(no output -- reviewer may have crashed or timed out)"
        echo ""
      fi
    done
  } > "$report_file"

  log "Polish report written to $report_file"
  POLISH_REPORT="$report_file"
}

`
}

// polishScriptPolishArchitect returns the run_polish_architect function.
func polishScriptPolishArchitect() string { //nolint:funlen // bash template string
	return `# --- Polish Architect ---
run_polish_architect() {
  local cycle_num="$1"
  local report_file="$2"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"
  local architect_log="$cycle_dir/polish-architect.log"

  log "Cycle $cycle_num: spawning polish architect"

  if [ "${POLISH_DRY_RUN:-}" = "1" ]; then
    log "DRY RUN: would spawn polish architect"
    return 0
  fi

  if [ -z "$report_file" ] || [ ! -s "$report_file" ]; then
    log "ERROR: polish report is empty or missing, skipping architect"
    return 1
  fi

  local prompt_file="$cycle_dir/polish-architect-prompt.md"
  {
    cat <<'ARCHITECT_HEADER_EOF'
You are a polish architect. Your job is NOT just to mechanically convert reviewer findings
into tickets. You are here to push the product toward exceptional quality and craft.

## Step 1: Load Context
Prime your session so you understand the product, its vision, and what has been built:

` + "```bash" + `
npx ca load-session
` + "```" + `

Then read the spec file to understand the product vision and goals:

` + "```bash" + `
cat "$SPEC_FILE"
` + "```" + `

Explore the codebase. Understand the current state -- what's built, what's working, what's rough.

## Step 2: Study the Audit Report
Read the polish report below. Reviewer findings are your STARTING POINT, not your ceiling.

## Step 3: Think Ambitiously
Go beyond the findings. Ask yourself:
- What would make a user fall in love with this product?
- Where does the current implementation feel "good enough" but not great?
- What micro-interactions, transitions, or details would elevate the experience?
- Are there rough edges the reviewers missed because they were checking a list?
- Does the product feel cohesive, or like a collection of features?
- Would you be proud to ship this? What would you fix first if not?

The polish loop exists to close the gap between "it works" and "it's exceptional."
Address ALL priority levels -- P0 critical issues, P1 quality gaps, AND P2 polish
opportunities. P2 items are not optional in a polish cycle -- they are the whole point.
Add your own P2/P3 discoveries beyond what reviewers found.

## Step 4: Create Improvement Epics
Group your improvements into well-structured epics (aim for 3-6). Each epic should:
- Have a clear, ambitious goal (not just "fix findings from reviewer X")
- Include specific acceptance criteria
- Cover a coherent bounded context (e.g., "interaction polish", "visual hierarchy", "performance")
- Mix reviewer findings WITH your own discoveries

For each epic:
` + "```bash" + `
bd create --title="Polish: <ambitious goal>" \
  --description="<what and why, acceptance criteria, specific files/areas>" \
  --type=epic --priority=2
` + "```" + `

Wire dependencies if needed: ` + "`bd dep add <dependent> <dependency>`" + `

## Step 5: Output Epic IDs
After creating all epics, output each ID on its own line:
POLISH_EPIC: <epic-id>

ARCHITECT_HEADER_EOF
    echo "## Polish Report"
    cat "$report_file"
    echo ""
    echo "## Meta-Epic"
    echo "Parent: $META_EPIC"
    echo ""
    echo "## Spec File"
    echo "Read this file for product vision: $SPEC_FILE"
  } > "$prompt_file"

  claude --model "$MODEL" \
    --dangerously-skip-permissions \
    --permission-mode auto \
    --output-format text \
    --verbose \
    -p - < "$prompt_file" > "$architect_log" 2>"$cycle_dir/polish-architect.stderr" || true

  # Extract created epic IDs
  POLISH_EPICS=""
  while IFS= read -r line; do
    local epic_id
    epic_id=$(echo "$line" | sed 's/^POLISH_EPIC: //')
    if [ -n "$epic_id" ]; then
      POLISH_EPICS="$POLISH_EPICS $epic_id"
    fi
  done < <(grep "^POLISH_EPIC: " "$architect_log" 2>/dev/null || true)
  POLISH_EPICS="${POLISH_EPICS# }"

  if [ -z "$POLISH_EPICS" ]; then
    log "Cycle $cycle_num: polish architect created no epics"
  else
    log "Cycle $cycle_num: polish architect created epics: $POLISH_EPICS"
  fi
}

`
}

// polishScriptInnerLoop returns the run_inner_loop function.
func polishScriptInnerLoop() string {
	return `# --- Inner Loop ---
run_inner_loop() {
  local cycle_num="$1"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"

  if [ -z "$POLISH_EPICS" ]; then
    log "Cycle $cycle_num: no epics to process -- skipping inner loop"
    return 0
  fi

  log "Cycle $cycle_num: generating inner infinity loop for epics: $POLISH_EPICS"

  local inner_script="$cycle_dir/inner-loop.sh"
  local epic_csv
  epic_csv=$(echo "$POLISH_EPICS" | tr ' ' ',')

  if [ "${POLISH_DRY_RUN:-}" = "1" ]; then
    log "DRY RUN: would run npx ca loop --epics $epic_csv"
    return 0
  fi

  npx ca loop --epics "$epic_csv" --model "$MODEL" --force -o "$inner_script" 2>"$cycle_dir/ca-loop-gen.stderr" || {
    log "ERROR: failed to generate inner loop script"
    return 1
  }

  log "Cycle $cycle_num: running inner infinity loop"
  bash "$inner_script" >"$cycle_dir/inner-loop.stdout" 2>"$cycle_dir/inner-loop.stderr" || {
    log "WARN: inner loop exited with non-zero status"
  }

  log "Cycle $cycle_num: inner loop completed"
}

`
}

// polishScriptMainLoop returns the main orchestration loop.
func polishScriptMainLoop() string {
	return `# --- Main Loop ---
detect_polish_reviewers

log "Starting polish loop: $CYCLES cycles"
echo "{\"status\":\"running\",\"cycles\":$CYCLES,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"

POLISH_EPICS=""
POLISH_REPORT=""

for ((cycle=1; cycle<=CYCLES; cycle++)); do
  log "=== Cycle $cycle/$CYCLES ==="
  POLISH_EPICS=""
  POLISH_REPORT=""
  echo "{\"status\":\"running\",\"cycle\":$cycle,\"cycles\":$CYCLES,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"

  # Step 1: Audit
  run_polish_audit "$cycle"

  # Step 2: Synthesize
  synthesize_report "$cycle"

  # Step 3: Polish Architect
  if [ -n "$POLISH_REPORT" ]; then
    run_polish_architect "$cycle" "$POLISH_REPORT" || log "WARN: polish architect failed for cycle $cycle"
  else
    log "WARN: no polish report produced, skipping architect for cycle $cycle"
  fi

  # Step 4: Inner Loop
  run_inner_loop "$cycle"

  log "=== Cycle $cycle/$CYCLES complete ==="
done

`
}

// polishScriptPostLoop returns the post-loop cleanup and push section.
func polishScriptPostLoop() string {
	return `# --- Post Loop ---
log "Polish loop completed: $CYCLES cycles"
echo "{\"status\":\"completed\",\"cycles\":$CYCLES,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"

# Commit and push results
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  log "Committing polish loop artifacts"
  git add docs/specs/polish-report-cycle-*.md agent_logs/.polish-status.json 2>/dev/null || true
  git commit -m "chore: polish loop cycle completion" 2>/dev/null || true
fi
if git remote get-url origin >/dev/null 2>&1; then
  log "Pushing results"
  git push 2>/dev/null || log "WARN: git push failed (non-fatal)"
fi

log "Done"
`
}
