package cli

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/nathandelacretaz/compound-agent/internal/memory"
	"github.com/nathandelacretaz/compound-agent/internal/setup"
	"github.com/nathandelacretaz/compound-agent/internal/util"
	"github.com/spf13/cobra"
)

// ========================== improve ==========================

func improveCmd() *cobra.Command {
	var (
		output    string
		maxIters  int
		budget    int
		model     string
		force     bool
		topics    string
	)

	cmd := &cobra.Command{
		Use:   "improve",
		Short: "Generate improvement loop script",
		RunE: func(cmd *cobra.Command, args []string) error {
			if output == "" {
				output = "improvement-loop.sh"
			}
			if !force {
				if _, err := os.Stat(output); err == nil {
					return fmt.Errorf("file %s already exists (use --force to overwrite)", output)
				}
			}

			topicFilter := ""
			if topics != "" {
				topicFilter = topics
			}

			script := generateImproveScript(maxIters, budget, model, topicFilter)

			if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
				return fmt.Errorf("create directory: %w", err)
			}
			if err := os.WriteFile(output, []byte(script), 0755); err != nil {
				return fmt.Errorf("write script: %w", err)
			}

			cmd.Printf("[ok] Generated improvement script: %s\n", output)
			cmd.Println("Run it with: bash " + output)
			return nil
		},
	}

	// init subcommand
	initCmd := &cobra.Command{
		Use:   "init",
		Short: "Create example improvement program",
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "improve"
			if v, _ := cmd.Flags().GetString("dir"); v != "" {
				dir = v
			}
			return createExampleImproveFile(cmd, dir)
		},
	}
	initCmd.Flags().String("dir", "improve", "Directory for improvement programs")
	cmd.AddCommand(initCmd)

	cmd.Flags().StringVarP(&output, "output", "o", "improvement-loop.sh", "Output script path")
	cmd.Flags().IntVar(&maxIters, "max-iters", 5, "Max iterations per topic")
	cmd.Flags().IntVar(&budget, "time-budget", 0, "Total time budget in seconds (0=unlimited)")
	cmd.Flags().StringVar(&model, "model", "claude-sonnet-4-6", "Claude model to use")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite existing script")
	cmd.Flags().StringVar(&topics, "topics", "", "Comma-separated topic names to run")
	return cmd
}

func createExampleImproveFile(cmd *cobra.Command, dir string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}

	example := `# Code Quality Improvement

## Goal
Improve code quality by fixing linting issues, adding missing type annotations,
and removing dead code.

## Validation
- All tests pass
- No new linting violations
- Changes are focused and minimal
`
	path := filepath.Join(dir, "code-quality.md")
	if _, err := os.Stat(path); err == nil {
		cmd.Printf("[info] %s already exists\n", path)
		return nil
	}
	if err := os.WriteFile(path, []byte(example), 0644); err != nil {
		return fmt.Errorf("write example: %w", err)
	}
	cmd.Printf("[ok] Created example improvement program: %s\n", path)
	return nil
}

func generateImproveScript(maxIters, timeBudget int, model, topicFilter string) string {
	timestamp := time.Now().Format(time.RFC3339)
	return fmt.Sprintf(`#!/usr/bin/env bash
# Improvement Loop - Generated by: ca improve
# Date: %s
# Iterates over improve/*.md programs to autonomously improve the codebase.
#
# Usage:
#   ./improvement-loop.sh
#   IMPROVE_DRY_RUN=1 ./improvement-loop.sh  # Preview without executing

set -euo pipefail

# Config
MAX_ITERS=%d
TIME_BUDGET=%d
MODEL="%s"
TOPIC_FILTER="%s"
LOG_DIR="agent_logs"
START_TIME=$(date +%%s)

mkdir -p "$LOG_DIR"

# --- Topic Discovery ---
get_topics() {
  local topics=()
  for f in improve/*.md; do
    [ -f "$f" ] || continue
    local name
    name=$(basename "$f" .md)
    if [ -n "$TOPIC_FILTER" ]; then
      echo "$TOPIC_FILTER" | tr ',' '\n' | grep -qx "$name" || continue
    fi
    topics+=("$name")
  done
  printf '%%s\n' "${topics[@]}"
}

# --- Prompt Builder ---
build_prompt() {
  local topic="$1"
  local file="improve/${topic}.md"
  echo "You are running in an autonomous improvement loop."
  echo ""
  echo "Read and implement the improvement program in: $file"
  echo ""
  echo "When done, output one of these markers on its own line:"
  echo "  IMPROVED        - Changes were made and tests pass"
  echo "  NO_IMPROVEMENT  - No meaningful improvements found"
  echo "  FAILED          - Could not complete the improvement"
}

# --- Marker Detection ---
detect_marker() {
  local file="$1"
  if grep -q "^IMPROVED$" "$file" 2>/dev/null; then echo "IMPROVED"; return; fi
  if grep -q "^NO_IMPROVEMENT$" "$file" 2>/dev/null; then echo "NO_IMPROVEMENT"; return; fi
  if grep -q "^FAILED$" "$file" 2>/dev/null; then echo "FAILED"; return; fi
  echo "UNKNOWN"
}

# --- Main Loop ---
COMPLETED=0
FAILED_COUNT=0
echo "[improve] Starting improvement loop"

for topic in $(get_topics); do
  echo "[improve] Topic: $topic"
  no_improve_streak=0

  for ((iter=1; iter<=MAX_ITERS; iter++)); do
    # Time budget check
    if [ "$TIME_BUDGET" -gt 0 ]; then
      elapsed=$(( $(date +%%s) - START_TIME ))
      if [ "$elapsed" -ge "$TIME_BUDGET" ]; then
        echo "[improve] Time budget exhausted"
        break 2
      fi
    fi

    echo "[improve] $topic iteration $iter/$MAX_ITERS"
    TRACE_FILE="$LOG_DIR/trace_improve_${topic}_$(date +%%Y%%m%%d_%%H%%M%%S).jsonl"
    MACRO_FILE="$LOG_DIR/macro_improve_${topic}_$(date +%%Y%%m%%d_%%H%%M%%S).txt"

    # Create git checkpoint
    git tag "improve/${topic}/iter-${iter}/pre" 2>/dev/null || true

    if [ "${IMPROVE_DRY_RUN:-}" = "1" ]; then
      echo "[improve] DRY RUN: would spawn claude for $topic"
      continue
    fi

    # Spawn Claude session
    PROMPT=$(build_prompt "$topic")
    claude --model "$MODEL" --output-format stream-json -p "$PROMPT" > "$TRACE_FILE" 2>/dev/null || true

    # Extract text and detect marker
    if command -v jq >/dev/null 2>&1; then
      jq -r 'select(.type=="assistant") | .message.content[]? | select(.type=="text") | .text' "$TRACE_FILE" > "$MACRO_FILE" 2>/dev/null || true
    fi

    MARKER=$(detect_marker "$MACRO_FILE")

    case "$MARKER" in
      IMPROVED)
        echo "[improve] $topic: improved (iteration $iter)"
        git add -A && git commit -m "improve($topic): iteration $iter" --no-verify 2>/dev/null || true
        COMPLETED=$((COMPLETED + 1))
        no_improve_streak=0
        ;;
      NO_IMPROVEMENT)
        echo "[improve] $topic: no improvement found"
        git checkout -- . 2>/dev/null || true
        no_improve_streak=$((no_improve_streak + 1))
        if [ "$no_improve_streak" -ge 2 ]; then
          echo "[improve] $topic: diminishing returns, moving on"
          break
        fi
        ;;
      FAILED|UNKNOWN)
        echo "[improve] $topic: failed"
        git checkout -- . 2>/dev/null || true
        FAILED_COUNT=$((FAILED_COUNT + 1))
        break
        ;;
    esac
  done
done

echo ""
echo "[improve] Summary: $COMPLETED improvements, $FAILED_COUNT failures"
`, timestamp, maxIters, timeBudget, model, topicFilter)
}

// ========================== loop ==========================

func loopCmd() *cobra.Command {
	var (
		output     string
		maxRetries int
		model      string
		force      bool
		epics      string
	)

	cmd := &cobra.Command{
		Use:   "loop",
		Short: "Generate infinity loop script for epic processing",
		RunE: func(cmd *cobra.Command, args []string) error {
			if output == "" {
				output = "infinity-loop.sh"
			}
			if !force {
				if _, err := os.Stat(output); err == nil {
					return fmt.Errorf("file %s already exists (use --force to overwrite)", output)
				}
			}

			script := generateLoopScript(maxRetries, model, epics)

			if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
				return fmt.Errorf("create directory: %w", err)
			}
			if err := os.WriteFile(output, []byte(script), 0755); err != nil {
				return fmt.Errorf("write script: %w", err)
			}

			cmd.Printf("[ok] Generated infinity loop script: %s\n", output)
			cmd.Println("Run it with: bash " + output)
			return nil
		},
	}

	cmd.Flags().StringVarP(&output, "output", "o", "infinity-loop.sh", "Output script path")
	cmd.Flags().IntVar(&maxRetries, "max-retries", 1, "Max retries per epic on failure")
	cmd.Flags().StringVar(&model, "model", "claude-sonnet-4-6", "Claude model to use")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite existing script")
	cmd.Flags().StringVar(&epics, "epics", "", "Comma-separated epic IDs to process")
	return cmd
}

func generateLoopScript(maxRetries int, model, epicIDs string) string {
	timestamp := time.Now().Format(time.RFC3339)
	bt := "`" // backtick for use in templates

	var b strings.Builder
	fmt.Fprintf(&b, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&b, "# Infinity Loop - Generated by: ca loop\n")
	fmt.Fprintf(&b, "# Date: %s\n", timestamp)
	fmt.Fprintf(&b, "# Autonomously processes beads epics via Claude Code sessions.\n")
	fmt.Fprintf(&b, "#\n# Usage:\n#   ./infinity-loop.sh\n#   LOOP_DRY_RUN=1 ./infinity-loop.sh\n\n")
	fmt.Fprintf(&b, "set -euo pipefail\n\n")
	fmt.Fprintf(&b, "# Config\nMAX_RETRIES=%d\nMODEL=\"%s\"\nEPIC_IDS=\"%s\"\nLOG_DIR=\"agent_logs\"\n\n", maxRetries, model, epicIDs)
	fmt.Fprintf(&b, "mkdir -p \"$LOG_DIR\"\n\n")

	// Epic selector
	b.WriteString(`# --- Epic Selector ---
get_next_epic() {
  if [ -n "$EPIC_IDS" ]; then
    for id in $(echo "$EPIC_IDS" | tr ',' ' '); do
      echo "$PROCESSED" | grep -qw "$id" && continue
      echo "$id"
      return
    done
  else
    bd ready --json 2>/dev/null | jq -r '.[0].id // empty' 2>/dev/null || true
  fi
}

`)

	// Prompt builder (uses bt variable for backticks)
	fmt.Fprintf(&b, "# --- Prompt Builder ---\nbuild_prompt() {\n  local epic_id=\"$1\"\n  cat <<PROMPT_EOF\n")
	fmt.Fprintf(&b, "You are running in an autonomous infinity loop. Your task is to fully implement a beads epic.\n\n")
	fmt.Fprintf(&b, "## Step 1: Load context\nRun these commands to prime your session:\n%s%s%sbash\nnpx ca load-session\nbd show $epic_id\n%s%s%s\n\n", bt, bt, bt, bt, bt, bt)
	fmt.Fprintf(&b, "## Step 2: Execute the workflow\n/compound:cook-it from plan -- Epic: $epic_id\n\n")
	fmt.Fprintf(&b, "## Step 3: On completion\n1. Close the epic: %sbd close $epic_id%s\n2. Commit and push all changes\n3. Output this marker on its own line:\n\nEPIC_COMPLETE\n\n", bt, bt)
	fmt.Fprintf(&b, "## Step 4: On failure\n1. Add a note: %sbd update $epic_id --notes \"Loop failed: <reason>\"%s\n2. Output this marker:\n\nEPIC_FAILED\n\n", bt, bt)
	fmt.Fprintf(&b, "## Step 5: On human required\nHUMAN_REQUIRED: <reason>\n\n")
	fmt.Fprintf(&b, "## Rules\n- Do NOT ask questions. Make reasonable decisions.\n- Do NOT stop early. Complete the full workflow.\n- If tests fail, fix them. Retry up to 3 times.\n- Commit incrementally.\n")
	fmt.Fprintf(&b, "PROMPT_EOF\n}\n\n")

	// Marker detection and rest of script
	b.WriteString(`# --- Marker Detection ---
detect_marker() {
  local file="$1"
  if grep -q "EPIC_COMPLETE" "$file" 2>/dev/null; then echo "EPIC_COMPLETE"; return; fi
  if grep -q "EPIC_FAILED" "$file" 2>/dev/null; then echo "EPIC_FAILED"; return; fi
  if grep -q "HUMAN_REQUIRED" "$file" 2>/dev/null; then echo "HUMAN_REQUIRED"; return; fi
  echo "UNKNOWN"
}

# --- Text Extractor ---
extract_text() {
  local file="$1" out="$2"
  if command -v jq >/dev/null 2>&1; then
    jq -r 'select(.type=="assistant") | .message.content[]? | select(.type=="text") | .text' "$file" > "$out" 2>/dev/null || true
  fi
}

# --- Observability ---
write_status() {
  echo "{\"epic\":\"$1\",\"attempt\":$2,\"status\":\"$3\",\"timestamp\":\"$(date -u +%FT%TZ)\"}" > "$LOG_DIR/status.json"
}

log_result() {
  echo "{\"epic\":\"$1\",\"result\":\"$2\",\"attempts\":$3,\"duration\":$4,\"timestamp\":\"$(date -u +%FT%TZ)\"}" >> "$LOG_DIR/exec.jsonl"
}

# --- Main Loop ---
COMPLETED=0
FAILED_COUNT=0
SKIPPED=0
PROCESSED=""

echo "[loop] Starting infinity loop"

while true; do
  EPIC_ID=$(get_next_epic)
  [ -z "$EPIC_ID" ] && break

  echo "[loop] Processing epic: $EPIC_ID"
  PROCESSED="$PROCESSED $EPIC_ID"
  EPIC_START=$(date +%s)
  RESULT="failed"

  for ((attempt=0; attempt<=MAX_RETRIES; attempt++)); do
    write_status "$EPIC_ID" "$attempt" "running"

    TRACE_FILE="$LOG_DIR/trace_${EPIC_ID}-$(date +%Y%m%d_%H%M%S).jsonl"
    MACRO_FILE="$LOG_DIR/macro_${EPIC_ID}-$(date +%Y%m%d_%H%M%S).txt"

    # Update .latest symlink
    ln -sf "$(basename "$TRACE_FILE")" "$LOG_DIR/.latest" 2>/dev/null || true

    if [ "${LOOP_DRY_RUN:-}" = "1" ]; then
      echo "[loop] DRY RUN: would process $EPIC_ID"
      RESULT="skipped"
      break
    fi

    # Spawn Claude session
    PROMPT=$(build_prompt "$EPIC_ID")
    claude --model "$MODEL" --output-format stream-json -p "$PROMPT" > "$TRACE_FILE" 2>/dev/null || true

    extract_text "$TRACE_FILE" "$MACRO_FILE"
    MARKER=$(detect_marker "$MACRO_FILE")

    # Fallback: check trace file if macro didn't have marker
    if [ "$MARKER" = "UNKNOWN" ]; then
      MARKER=$(detect_marker "$TRACE_FILE")
    fi

    case "$MARKER" in
      EPIC_COMPLETE)
        echo "[loop] $EPIC_ID: complete"
        RESULT="complete"
        break
        ;;
      HUMAN_REQUIRED)
        echo "[loop] $EPIC_ID: human action required"
        RESULT="human_required"
        SKIPPED=$((SKIPPED + 1))
        break
        ;;
      EPIC_FAILED|UNKNOWN)
        echo "[loop] $EPIC_ID: failed (attempt $((attempt+1)))"
        if [ "$attempt" -lt "$MAX_RETRIES" ]; then
          echo "[loop] Retrying in 5s..."
          sleep 5
        fi
        ;;
    esac
  done

  EPIC_DURATION=$(( $(date +%s) - EPIC_START ))

  case "$RESULT" in
    complete) COMPLETED=$((COMPLETED + 1)) ;;
    failed|unknown) FAILED_COUNT=$((FAILED_COUNT + 1)) ;;
  esac

  write_status "$EPIC_ID" "$attempt" "$RESULT"
  log_result "$EPIC_ID" "$RESULT" "$((attempt+1))" "$EPIC_DURATION"
done

echo ""
echo "[loop] Summary: $COMPLETED completed, $FAILED_COUNT failed, $SKIPPED skipped"
`)

	return b.String()
}

// ========================== watch ==========================

func watchCmd() *cobra.Command {
	var (
		epicID  string
		follow  bool
		improve bool
		logDir  string
	)

	cmd := &cobra.Command{
		Use:   "watch",
		Short: "Tail and pretty-print live trace from infinity loop sessions",
		RunE: func(cmd *cobra.Command, args []string) error {
			if logDir == "" {
				repoRoot := util.GetRepoRoot()
				logDir = filepath.Join(repoRoot, "agent_logs")
			}

			var traceFile string

			if epicID != "" {
				traceFile = findTraceForEpic(logDir, epicID)
				if traceFile == "" {
					cmd.Printf("[error] No trace file found for epic: %s\n", epicID)
					return nil
				}
			} else if improve {
				traceFile = findLatestTrace(logDir, "trace_improve_")
				if traceFile == "" {
					cmd.Println("[info] No improvement trace found.")
					return nil
				}
			} else {
				traceFile = findLatestTrace(logDir, "trace_")
				if traceFile == "" {
					cmd.Println("[info] No active trace found. Run `ca loop` first.")
					return nil
				}
			}

			cmd.Printf("[info] Watching: %s\n", traceFile)

			if follow {
				return tailFollow(cmd, traceFile)
			}
			return readAndFormat(cmd, traceFile)
		},
	}

	cmd.Flags().StringVar(&epicID, "epic", "", "Watch a specific epic trace")
	cmd.Flags().BoolVar(&follow, "follow", true, "Follow the file (tail -f)")
	cmd.Flags().BoolVar(&improve, "improve", false, "Watch improvement loop traces")
	cmd.Flags().StringVar(&logDir, "log-dir", "", "Log directory (default: agent_logs/)")
	// Support --no-follow
	cmd.Flags().Lookup("follow").NoOptDefVal = "true"
	return cmd
}

func findLatestTrace(logDir, prefix string) string {
	if _, err := os.Stat(logDir); os.IsNotExist(err) {
		return ""
	}

	// Check .latest symlink first
	latestPath := filepath.Join(logDir, ".latest")
	if target, err := os.Readlink(latestPath); err == nil {
		resolved := filepath.Join(logDir, target)
		if _, err := os.Stat(resolved); err == nil && strings.HasPrefix(target, prefix) {
			return resolved
		}
	}

	// Fallback: find most recent file
	entries, err := os.ReadDir(logDir)
	if err != nil {
		return ""
	}

	var matches []string
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), prefix) && strings.HasSuffix(e.Name(), ".jsonl") {
			matches = append(matches, e.Name())
		}
	}
	sort.Sort(sort.Reverse(sort.StringSlice(matches)))
	if len(matches) > 0 {
		return filepath.Join(logDir, matches[0])
	}
	return ""
}

func findTraceForEpic(logDir, epicID string) string {
	prefix := fmt.Sprintf("trace_%s-", epicID)
	return findLatestTrace(logDir, prefix)
}

// streamEvent represents a parsed stream-json event.
type streamEvent struct {
	Type         string `json:"type"`
	Timestamp    string `json:"timestamp,omitempty"`
	ContentBlock *struct {
		Type string `json:"type"`
		Name string `json:"name,omitempty"`
	} `json:"content_block,omitempty"`
	Delta *struct {
		Type string `json:"type"`
		Text string `json:"text,omitempty"`
	} `json:"delta,omitempty"`
	Message *struct {
		Usage *struct {
			InputTokens  int `json:"input_tokens,omitempty"`
			OutputTokens int `json:"output_tokens,omitempty"`
		} `json:"usage,omitempty"`
	} `json:"message,omitempty"`
	Usage *struct {
		OutputTokens int `json:"output_tokens,omitempty"`
	} `json:"usage,omitempty"`
	Result string `json:"result,omitempty"`
}

func formatStreamEvent(event streamEvent) string {
	ts := formatEventTime(event.Timestamp)

	switch event.Type {
	case "content_block_start":
		if event.ContentBlock != nil {
			if event.ContentBlock.Type == "tool_use" {
				return fmt.Sprintf("%s TOOL    %s", ts, event.ContentBlock.Name)
			}
			if event.ContentBlock.Type == "thinking" {
				return fmt.Sprintf("%s THINK   thinking...", ts)
			}
		}
	case "content_block_delta":
		if event.Delta != nil && event.Delta.Type == "text_delta" {
			text := event.Delta.Text
			text = strings.ReplaceAll(text, "\n", " ")
			if len(text) > 60 {
				text = text[:57] + "..."
			}
			return fmt.Sprintf("%s TEXT    %s", ts, text)
		}
	case "message_delta":
		if event.Usage != nil && event.Usage.OutputTokens > 0 {
			return fmt.Sprintf("%s TOKENS  %d out (final)", ts, event.Usage.OutputTokens)
		}
	case "message_start":
		if event.Message != nil && event.Message.Usage != nil {
			return fmt.Sprintf("%s TOKENS  %d in / %d out", ts, event.Message.Usage.InputTokens, event.Message.Usage.OutputTokens)
		}
	case "result":
		if event.Result != "" {
			markers := []string{"EPIC_COMPLETE", "EPIC_FAILED", "HUMAN_REQUIRED", "NO_IMPROVEMENT", "IMPROVED", "FAILED"}
			for _, m := range markers {
				if strings.Contains(event.Result, m) {
					line := event.Result
					for _, l := range strings.Split(event.Result, "\n") {
						if strings.Contains(l, m) {
							line = l
							break
						}
					}
					if len(line) > 120 {
						line = line[:117] + "..."
					}
					return fmt.Sprintf("%s MARKER  %s", ts, line)
				}
			}
		}
	}
	return ""
}

func formatEventTime(timestamp string) string {
	if timestamp == "" {
		return time.Now().Format("15:04:05")
	}
	t, err := time.Parse(time.RFC3339, timestamp)
	if err != nil {
		return time.Now().Format("15:04:05")
	}
	return t.Format("15:04:05")
}

func readAndFormat(cmd *cobra.Command, path string) error {
	f, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open trace: %w", err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		var event streamEvent
		if err := json.Unmarshal([]byte(line), &event); err != nil {
			continue
		}
		formatted := formatStreamEvent(event)
		if formatted != "" {
			cmd.Println(formatted)
		}
	}
	return scanner.Err()
}

func tailFollow(cmd *cobra.Command, path string) error {
	// For simplicity, just read and format (follow mode would need goroutines + fsnotify)
	// In practice, the bash script's `tail -f` is more reliable
	return readAndFormat(cmd, path)
}

// ========================== audit ==========================

type auditFinding struct {
	File     string `json:"file,omitempty"`
	Issue    string `json:"issue"`
	Severity string `json:"severity"` // "error", "warning", "info"
	Source   string `json:"source"`   // "rule", "pattern", "lesson"
}

type auditReport struct {
	Findings []auditFinding `json:"findings"`
	Summary  struct {
		Errors   int `json:"errors"`
		Warnings int `json:"warnings"`
		Infos    int `json:"infos"`
	} `json:"summary"`
}

func auditCmd() *cobra.Command {
	var (
		repoRoot string
		jsonOut  bool
	)

	cmd := &cobra.Command{
		Use:   "audit",
		Short: "Run audit checks against the codebase",
		RunE: func(cmd *cobra.Command, args []string) error {
			if repoRoot == "" {
				repoRoot = util.GetRepoRoot()
			}

			report := runAuditChecks(repoRoot)

			if jsonOut {
				data, _ := json.MarshalIndent(report, "", "  ")
				cmd.Println(string(data))
				return nil
			}

			for _, f := range report.Findings {
				label := strings.ToUpper(f.Severity)
				filePart := ""
				if f.File != "" {
					filePart = " " + f.File
				}
				cmd.Printf("%s [%s]%s -- %s\n", label, f.Source, filePart, f.Issue)
			}

			cmd.Println()
			cmd.Printf("Audit: %d finding(s), %d error(s), %d warning(s), %d info(s)\n",
				len(report.Findings), report.Summary.Errors, report.Summary.Warnings, report.Summary.Infos)
			return nil
		},
	}

	cmd.Flags().StringVar(&repoRoot, "repo-root", "", "Repository root")
	cmd.Flags().BoolVar(&jsonOut, "json", false, "Output as JSON")
	return cmd
}

func runAuditChecks(repoRoot string) auditReport {
	var findings []auditFinding

	// Rule checks
	// 1. .claude/ directory
	if _, err := os.Stat(filepath.Join(repoRoot, ".claude")); os.IsNotExist(err) {
		findings = append(findings, auditFinding{
			Issue:    ".claude/ directory missing — run ca init",
			Severity: "error",
			Source:   "rule",
		})
	}

	// 2. Lessons index
	indexPath := filepath.Join(repoRoot, ".claude", "lessons", "index.jsonl")
	if _, err := os.Stat(indexPath); os.IsNotExist(err) {
		findings = append(findings, auditFinding{
			Issue:    "Lessons index missing — run ca init",
			Severity: "error",
			Source:   "rule",
		})
	}

	// 3. Hooks configured
	settingsPath := filepath.Join(repoRoot, ".claude", "settings.json")
	settings, err := setup.ReadClaudeSettings(settingsPath)
	if err != nil || !setup.HasAllHooks(settings) {
		findings = append(findings, auditFinding{
			Issue:    "Claude Code hooks not fully configured — run ca setup claude",
			Severity: "warning",
			Source:   "rule",
		})
	}

	// 4. .gitignore
	gitignorePath := filepath.Join(repoRoot, ".claude", ".gitignore")
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		findings = append(findings, auditFinding{
			Issue:    ".claude/.gitignore missing — run ca init",
			Severity: "warning",
			Source:   "rule",
		})
	}

	// 5. Check for lessons with potential issues
	result, err := memory.ReadMemoryItems(repoRoot)
	if err == nil {
		oldCount := 0
		threshold := time.Now().AddDate(0, 0, -90)
		for _, item := range result.Items {
			created, err := time.Parse(time.RFC3339, item.Created)
			if err == nil && created.Before(threshold) {
				oldCount++
			}
		}
		if oldCount > 0 {
			findings = append(findings, auditFinding{
				Issue:    fmt.Sprintf("%d lesson(s) are over 90 days old — review for validity", oldCount),
				Severity: "info",
				Source:   "lesson",
			})
		}
		if len(result.Items) > 50 {
			findings = append(findings, auditFinding{
				Issue:    fmt.Sprintf("%d lessons in index — consider running ca compact", len(result.Items)),
				Severity: "info",
				Source:   "lesson",
			})
		}
	}

	// Build summary
	report := auditReport{Findings: findings}
	if report.Findings == nil {
		report.Findings = []auditFinding{}
	}
	for _, f := range findings {
		switch f.Severity {
		case "error":
			report.Summary.Errors++
		case "warning":
			report.Summary.Warnings++
		case "info":
			report.Summary.Infos++
		}
	}
	return report
}

func registerScriptCommands(rootCmd *cobra.Command) {
	rootCmd.AddCommand(improveCmd())
	rootCmd.AddCommand(loopCmd())
	rootCmd.AddCommand(watchCmd())
	rootCmd.AddCommand(auditCmd())
}
