package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/nathandelacretaz/compound-agent/internal/util"
	"github.com/spf13/cobra"
)

// polishCmdOptions captures all flag values for the polish command.
type polishCmdOptions struct {
	output, model, metaEpic, spec, reviewers string
	cycles                                   int
	force                                    bool
}

func polishCmd() *cobra.Command {
	var o polishCmdOptions

	cmd := &cobra.Command{
		Use:   "polish",
		Short: "Generate polish loop script for iterative quality refinement",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPolish(cmd, &o)
		},
	}

	cmd.Flags().StringVarP(&o.output, "output", "o", "polish-loop.sh", "Output script path")
	cmd.Flags().IntVar(&o.cycles, "cycles", 0, "Number of polish cycles (required)")
	cmd.Flags().StringVar(&o.metaEpic, "meta-epic", "", "Meta-epic ID to polish (required)")
	cmd.Flags().StringVar(&o.spec, "spec", "", "Path to spec file for reviewer context (required)")
	cmd.Flags().StringVar(&o.reviewers, "reviewers", "", "Comma-separated reviewers (claude-opus,claude-sonnet,gemini,codex) (required)")
	cmd.Flags().StringVar(&o.model, "model", "claude-opus-4-6[1m]", "Claude model for architect and inner loop sessions")
	cmd.Flags().BoolVar(&o.force, "force", false, "Overwrite existing script")
	return cmd
}

// validatePolishOptions checks required flags and reviewer names.
func validatePolishOptions(o *polishCmdOptions) ([]string, error) {
	if o.cycles < 1 {
		return nil, fmt.Errorf("--cycles is required and must be >= 1")
	}
	if o.metaEpic == "" {
		return nil, fmt.Errorf("--meta-epic is required")
	}
	if o.spec == "" {
		return nil, fmt.Errorf("--spec is required")
	}
	if o.reviewers == "" {
		return nil, fmt.Errorf("--reviewers is required")
	}
	reviewerList := strings.Split(o.reviewers, ",")
	if err := validateReviewers(reviewerList); err != nil {
		return nil, err
	}
	return reviewerList, nil
}

func runPolish(cmd *cobra.Command, o *polishCmdOptions) error {
	reviewerList, err := validatePolishOptions(o)
	if err != nil {
		return err
	}

	output := o.output
	if !o.force {
		if _, err := os.Stat(output); err == nil {
			return fmt.Errorf("file %s already exists (use --force to overwrite)", output)
		}
	}

	script := generatePolishScript(polishGenerateOptions{
		cycles:    o.cycles,
		model:     o.model,
		metaEpic:  o.metaEpic,
		spec:      o.spec,
		reviewers: reviewerList,
	})

	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}
	if err := os.WriteFile(output, []byte(script), 0755); err != nil {
		return fmt.Errorf("write script: %w", err)
	}
	cmd.Printf("[ok] Generated polish loop script: %s\n", output)
	cmd.Println("Run it with: bash " + output)
	return nil
}

// polishGenerateOptions holds all options for generating the polish script.
type polishGenerateOptions struct {
	cycles    int
	model     string
	metaEpic  string
	spec      string
	reviewers []string
}

func generatePolishScript(opts polishGenerateOptions) string {
	escapedModel := util.ShellEscape(opts.model)
	escapedMetaEpic := util.ShellEscape(opts.metaEpic)
	escapedSpec := util.ShellEscape(opts.spec)
	escapedReviewers := util.ShellEscape(strings.Join(opts.reviewers, " "))

	config := polishScriptConfig(opts.cycles, escapedModel, escapedMetaEpic, escapedSpec, escapedReviewers)
	logFn := polishScriptLogFunction()
	crashHandler := polishScriptCrashHandler()
	prereqs := polishScriptPrerequisites()
	reviewerDetection := polishScriptReviewerDetection()
	auditPrompt := polishScriptAuditPrompt()
	spawnReviewers := polishScriptSpawnReviewers()
	synthesize := polishScriptSynthesizeReport()
	miniArchitect := polishScriptMiniArchitect()
	innerLoop := polishScriptInnerLoop()
	mainLoop := polishScriptMainLoop()
	postLoop := polishScriptPostLoop()

	return config + logFn + crashHandler + prereqs +
		reviewerDetection + auditPrompt + spawnReviewers +
		synthesize + miniArchitect + innerLoop + mainLoop + postLoop
}

func polishScriptConfig(cycles int, escapedModel, escapedMetaEpic, escapedSpec, escapedReviewers string) string {
	timestamp := time.Now().Format(time.RFC3339)
	return fmt.Sprintf(`#!/usr/bin/env bash
# Polish Loop - Generated by: ca polish
# Date: %s
# Iterates N cycles of: audit fleet → mini-architect → inner infinity loop
#
# Usage:
#   ./polish-loop.sh
#   POLISH_DRY_RUN=1 ./polish-loop.sh  # Preview without executing

set -euo pipefail

# Config
CYCLES=%d
MODEL=%s
META_EPIC=%s
SPEC_FILE=%s
CONFIGURED_REVIEWERS=%s
LOG_DIR="agent_logs"

mkdir -p "$LOG_DIR"

`, timestamp, cycles, escapedModel, escapedMetaEpic, escapedSpec, escapedReviewers)
}

func polishScriptCrashHandler() string {
	return `# --- Crash Handler ---
_polish_cleanup() {
  local exit_code=$?
  if [ $exit_code -ne 0 ]; then
    log "Polish loop crashed with exit code $exit_code"
    echo "{\"status\":\"crashed\",\"exit_code\":$exit_code,\"cycle\":${cycle:-0},\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"
    exit $exit_code
  fi
}
trap _polish_cleanup EXIT

`
}

func polishScriptPrerequisites() string {
	return `# --- Prerequisites ---
command -v claude >/dev/null 2>&1 || { echo "ERROR: claude CLI not found"; exit 1; }
command -v bd >/dev/null 2>&1 || { echo "ERROR: bd CLI not found"; exit 1; }
command -v ca >/dev/null 2>&1 || { echo "ERROR: ca CLI not found (needed for inner loop)"; exit 1; }
[ -f "$SPEC_FILE" ] || { log "ERROR: spec file not found: $SPEC_FILE"; exit 1; }

`
}

func polishScriptLogFunction() string {
	return `# --- Logging ---
log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] [polish] $*" >&2
}

`
}

func polishScriptReviewerDetection() string {
	return `# --- Reviewer Detection ---
detect_polish_reviewers() {
  AVAILABLE_REVIEWERS=""
  for reviewer in $CONFIGURED_REVIEWERS; do
    local cli_name
    case "$reviewer" in
      claude-sonnet|claude-opus) cli_name="claude" ;;
      gemini)                    cli_name="gemini" ;;
      codex)                     cli_name="codex" ;;
      *) log "WARN: unknown reviewer $reviewer"; continue ;;
    esac
    if ! command -v "$cli_name" >/dev/null 2>&1; then
      log "WARN: $reviewer configured but $cli_name CLI not found — skipping"
      continue
    fi
    AVAILABLE_REVIEWERS="$AVAILABLE_REVIEWERS $reviewer"
  done
  AVAILABLE_REVIEWERS="${AVAILABLE_REVIEWERS# }"
  if [ -z "$AVAILABLE_REVIEWERS" ]; then
    log "ERROR: no reviewer CLIs available"
    exit 1
  fi
  log "Available reviewers: $AVAILABLE_REVIEWERS"
}

`
}

func polishScriptAuditPrompt() string { //nolint:funlen // bash template string
	return `# --- Audit Prompt (BGT Checklist) ---
build_audit_prompt() {
  local cycle_num="$1"
  local spec_content
  spec_content=$(cat "$SPEC_FILE" 2>/dev/null || echo "(spec file not found)")

  cat <<'AUDIT_PROMPT_EOF'
You are a senior quality auditor performing a holistic review of the entire implementation.

## Your Task
Evaluate the FULL codebase against the Build Great Things pre-ship quality checklist below.
Do NOT focus on recent diffs — review the entire implementation holistically.
Produce a structured report with P0/P1/P2 findings.

## Build Great Things Pre-Ship Checklist

### States (5 required per data view)
- [ ] loading state — skeleton or spinner while data fetches
- [ ] empty state — helpful message and CTA when no data exists
- [ ] error state — clear error message with recovery action
- [ ] offline state — graceful degradation when network unavailable
- [ ] partial data state — sensible rendering with incomplete data

### Interaction
- [ ] hover/active/focus/disabled states defined for all interactive elements
- [ ] focus styles visible and accessible (not just outline: none)
- [ ] press feedback — visual response within 100ms
- [ ] validation feedback — inline, immediate, specific
- [ ] page transitions — smooth, purposeful, not jarring

### Visual Craft
- [ ] 3+ levels of typography hierarchy (size, weight, color)
- [ ] de-emphasis used (not everything can be bold/primary)
- [ ] geometric spacing scale (4/8/16/24/32/48/64) — no arbitrary values
- [ ] no borders where spacing, background color, or shadow would work
- [ ] consistent elevation/shadow scale
- [ ] semantic color tokens (not raw hex)
- [ ] scroll animations — choreographed, not just fade-in
- [ ] optimized images — proper format, sizing, lazy loading
- [ ] consistent icon style and sizing

### Responsiveness
- [ ] mobile is first-class (different IA, content priority, interaction patterns)
- [ ] 44x44px minimum touch targets
- [ ] fluid typography (clamp or viewport units)
- [ ] no horizontal scroll on any breakpoint

### Performance
- [ ] Core Web Vitals: LCP < 2.5s, INP < 200ms, CLS < 0.1
- [ ] font loading strategy (font-display, preload, size-adjust fallbacks)
- [ ] above-fold content renders without JavaScript where possible

### Accessibility
- [ ] semantic HTML elements used (not div soup)
- [ ] ARIA only where semantic HTML insufficient (minimal ARIA)
- [ ] color contrast meets WCAG AA (4.5:1 for text)
- [ ] prefers-reduced-motion respected
- [ ] live region announcements for dynamic content

### Completeness
- [ ] 404 page designed (not default)
- [ ] favicon and Open Graph tags present
- [ ] print styles or print-friendly view

### Common AI Laziness Anti-Patterns
- [ ] NOT shallow component design — components have deep interfaces, not just pass-through props
- [ ] NOT generic UI — curated palettes, specific typeface pairings, deliberate whitespace
- [ ] NOT skipping polish phases — motion and performance phases are mandatory
- [ ] NOT first-design-only — design it twice before committing
- [ ] NOT missing visual hierarchy — use all three channels: size, weight, color
- [ ] NOT edge states only on happy path — empty/loading/error/partial/offline are design surfaces
- [ ] NOT flat interactions — every click/hover/scroll needs feedback
- [ ] NOT cookie-cutter layouts — vary section structures, use negative space
- [ ] NOT borders everywhere — try spacing, background color, shadows first
- [ ] NOT afterthought mobile — mobile needs different IA, content priority, interaction patterns
- [ ] NOT ignoring font loading — font-display strategy, preloading, size-adjust fallbacks
- [ ] NOT arbitrary spacing — use geometric scale only

## Output Format
Structure your report as:

### P0 — Must Fix (blocks quality)
- Finding description with file/line references

### P1 — Should Fix (significant quality gap)
- Finding description with file/line references

### P2 — Nice to Fix (polish opportunity)
- Finding description with file/line references

### Summary
- Overall assessment of craft quality (1-2 sentences)
- Top 3 highest-impact improvements

AUDIT_PROMPT_EOF

  echo ""
  echo "## Spec Context"
  echo "$spec_content"
  echo ""
  echo "## Cycle"
  echo "This is polish cycle $cycle_num of $CYCLES."
}

`
}

func polishScriptSpawnReviewers() string { //nolint:funlen // bash template string
	return `# --- Spawn Reviewers ---
run_polish_audit() {
  local cycle_num="$1"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"
  mkdir -p "$cycle_dir"

  log "Cycle $cycle_num: building audit prompt"
  local prompt_file="$cycle_dir/audit-prompt.md"
  build_audit_prompt "$cycle_num" > "$prompt_file"

  log "Cycle $cycle_num: spawning reviewers"
  for reviewer in $AVAILABLE_REVIEWERS; do
    local report="$cycle_dir/$reviewer-report.md"
    local cli_name model_flag

    case "$reviewer" in
      claude-opus)
        cli_name="claude"
        model_flag="--model claude-opus-4-6"
        ;;
      claude-sonnet)
        cli_name="claude"
        model_flag="--model claude-sonnet-4-6"
        ;;
      gemini)
        cli_name="gemini"
        model_flag=""
        ;;
      codex)
        cli_name="codex"
        model_flag=""
        ;;
    esac

    if [ "${POLISH_DRY_RUN:-}" = "1" ]; then
      log "DRY RUN: would spawn $reviewer"
      echo "(dry run — no actual review)" > "$report"
      continue
    fi

    case "$reviewer" in
      claude-opus|claude-sonnet)
        claude $model_flag \
          --dangerously-skip-permissions \
          --output-format text \
          -p - < "$prompt_file" > "$report" 2>"$cycle_dir/$reviewer.stderr" &
        ;;
      gemini)
        gemini --yolo \
          < "$prompt_file" \
          > "$report" 2>"$cycle_dir/$reviewer.stderr" &
        ;;
      codex)
        codex exec --full-auto \
          -o "$report" -- - < "$prompt_file" 2>"$cycle_dir/$reviewer.stderr" &
        ;;
    esac
    log "Spawned $reviewer (PID $!)"
  done

  log "Waiting for all reviewers to complete"
  wait
  log "All reviewers completed for cycle $cycle_num"
}

`
}

func polishScriptSynthesizeReport() string {
	return `# --- Synthesize Report ---
synthesize_report() {
  local cycle_num="$1"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"
  local report_file="docs/specs/polish-report-cycle-${cycle_num}.md"

  mkdir -p "$(dirname "$report_file")"

  log "Synthesizing polish report for cycle $cycle_num"

  {
    echo "# Polish Report — Cycle $cycle_num"
    echo ""
    echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    for reviewer in $AVAILABLE_REVIEWERS; do
      local report="$cycle_dir/$reviewer-report.md"
      if [ -s "$report" ]; then
        echo "## $reviewer"
        echo ""
        cat "$report"
        echo ""
      else
        echo "## $reviewer"
        echo ""
        echo "(no output — reviewer may have crashed or timed out)"
        echo ""
      fi
    done
  } > "$report_file"

  log "Polish report written to $report_file"
  POLISH_REPORT="$report_file"
}

`
}

func polishScriptMiniArchitect() string { //nolint:funlen // bash template string
	return `# --- Mini-Architect ---
run_mini_architect() {
  local cycle_num="$1"
  local report_file="$2"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"
  local architect_log="$cycle_dir/mini-architect.log"

  log "Cycle $cycle_num: spawning mini-architect"

  if [ "${POLISH_DRY_RUN:-}" = "1" ]; then
    log "DRY RUN: would spawn mini-architect"
    return 0
  fi

  # Build prompt file (quoted heredoc prevents shell expansion of report content)
  local prompt_file="$cycle_dir/mini-architect-prompt.md"
  {
    cat <<'ARCHITECT_HEADER_EOF'
You are a mini-architect for a polish cycle.

## Your Task
Read the polish report below and create improvement epic beads for the findings.

## Instructions
1. Read the polish report carefully
2. Group related findings into improvement epics (aim for 2-5 epics)
3. For each epic, run: bd create --title="Polish: <summary>" --description="<findings>" --type=epic --priority=2
4. Wire dependencies between epics if needed: bd dep add <dependent> <dependency>
5. Output the created epic IDs, one per line

ARCHITECT_HEADER_EOF
    echo "## Polish Report"
    cat "$report_file"
    echo ""
    echo "## Meta-Epic"
    echo "Parent: $META_EPIC"
    echo ""
    echo "## Output Format"
    echo "After creating all epics, output each ID on its own line:"
    echo "POLISH_EPIC: <epic-id>"
  } > "$prompt_file"

  claude --model "$MODEL" \
    --dangerously-skip-permissions \
    --output-format text \
    -p - < "$prompt_file" > "$architect_log" 2>"$cycle_dir/mini-architect.stderr" || true

  # Extract created epic IDs
  POLISH_EPICS=""
  while IFS= read -r line; do
    local epic_id
    epic_id=$(echo "$line" | sed 's/^POLISH_EPIC: //')
    if [ -n "$epic_id" ]; then
      POLISH_EPICS="$POLISH_EPICS $epic_id"
    fi
  done < <(grep "^POLISH_EPIC: " "$architect_log" 2>/dev/null || true)
  POLISH_EPICS="${POLISH_EPICS# }"

  if [ -z "$POLISH_EPICS" ]; then
    log "Cycle $cycle_num: mini-architect created no epics"
  else
    log "Cycle $cycle_num: mini-architect created epics: $POLISH_EPICS"
  fi
}

`
}

func polishScriptInnerLoop() string {
	return `# --- Inner Loop ---
run_inner_loop() {
  local cycle_num="$1"
  local cycle_dir="$LOG_DIR/polish-cycle-$cycle_num"

  if [ -z "$POLISH_EPICS" ]; then
    log "Cycle $cycle_num: no epics to process — skipping inner loop"
    return 0
  fi

  log "Cycle $cycle_num: generating inner infinity loop for epics: $POLISH_EPICS"

  local inner_script="$cycle_dir/inner-loop.sh"
  local epic_csv
  epic_csv=$(echo "$POLISH_EPICS" | tr ' ' ',')

  if [ "${POLISH_DRY_RUN:-}" = "1" ]; then
    log "DRY RUN: would run ca loop --epics $epic_csv"
    return 0
  fi

  ca loop --epics "$epic_csv" --model "$MODEL" --force -o "$inner_script" 2>"$cycle_dir/ca-loop-gen.stderr" || {
    log "ERROR: failed to generate inner loop script"
    return 1
  }

  log "Cycle $cycle_num: running inner infinity loop"
  bash "$inner_script" >"$cycle_dir/inner-loop.stdout" 2>"$cycle_dir/inner-loop.stderr" || {
    log "WARN: inner loop exited with non-zero status"
  }

  log "Cycle $cycle_num: inner loop completed"
}

`
}

func polishScriptMainLoop() string {
	return `# --- Main Loop ---
detect_polish_reviewers

log "Starting polish loop: $CYCLES cycles"
echo "{\"status\":\"running\",\"cycles\":$CYCLES,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"

POLISH_EPICS=""

for ((cycle=1; cycle<=CYCLES; cycle++)); do
  log "=== Cycle $cycle/$CYCLES ==="
  POLISH_EPICS=""
  echo "{\"status\":\"running\",\"cycle\":$cycle,\"cycles\":$CYCLES,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"

  # Step 1: Audit
  run_polish_audit "$cycle"

  # Step 2: Synthesize
  synthesize_report "$cycle"

  # Step 3: Mini-Architect
  run_mini_architect "$cycle" "$POLISH_REPORT"

  # Step 4: Inner Loop
  run_inner_loop "$cycle"

  log "=== Cycle $cycle/$CYCLES complete ==="
done

`
}

func polishScriptPostLoop() string {
	return `# --- Post Loop ---
log "Polish loop completed: $CYCLES cycles"
echo "{\"status\":\"completed\",\"cycles\":$CYCLES,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$LOG_DIR/.polish-status.json"

# Commit and push results
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  log "Committing polish loop artifacts"
  git add docs/specs/polish-report-cycle-*.md agent_logs/.polish-status.json 2>/dev/null || true
  git commit -m "chore: polish loop cycle completion" 2>/dev/null || true
fi
if git remote get-url origin >/dev/null 2>&1; then
  log "Pushing results"
  git push 2>/dev/null || log "WARN: git push failed (non-fatal)"
fi

log "Done"
`
}
