/**
 * Improve command: generate improvement loop script for autonomous codebase improvement.
 *
 * Generates a bash script that iterates over improve/*.md programs,
 * spawning Claude Code sessions to make focused improvements.
 */

import { existsSync } from 'node:fs';
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import type { Command } from 'commander';

import {
  buildTopicDiscovery,
  buildImprovePrompt,
  buildImproveMarkerDetection,
  buildImproveObservability,
  buildImproveMainLoop,
} from './improve-templates.js';
import { buildStreamExtractor } from './loop-templates.js';
import { out } from './shared.js';

/** Safe pattern for topic names */
export const TOPIC_NAME_PATTERN = /^[a-zA-Z0-9_-]+$/;

/** Default Claude model */
const DEFAULT_MODEL = 'claude-opus-4-6';

/** Safe pattern for model names: alphanumeric, hyphens, underscores, dots, colons, slashes */
const MODEL_PATTERN = /^[a-zA-Z0-9_.:/-]+$/;

export interface ImproveScriptOptions {
  topics?: string[];        // specific topics to run (default: all improve/*.md)
  maxIters: number;         // max iterations per topic
  timeBudget: number;       // total time budget in seconds (0 = unlimited)
  model: string;            // claude model to use
}

interface ImproveOptions {
  topics?: string[];
  output?: string;
  maxIters?: string;
  timeBudget?: string;
  model?: string;
  force?: boolean;
  dryRun?: boolean;
  init?: boolean;
}

function buildImproveScriptHeader(timestamp: string, maxIters: number, timeBudget: number, model: string, topicFilter: string): string {
  return `#!/usr/bin/env bash
# Improvement Loop - Generated by: ca improve
# Date: ${timestamp}
# Iterates over improve/*.md programs to autonomously improve the codebase.
#
# Usage:
#   ./improvement-loop.sh
#   IMPROVE_DRY_RUN=1 ./improvement-loop.sh  # Preview without executing

set -euo pipefail

# Config
MAX_ITERS=${maxIters}
TIME_BUDGET=${timeBudget}
MODEL="${model}"
TOPIC_FILTER="${topicFilter}"
LOG_DIR="agent_logs"

# Helpers
timestamp() { date '+%Y-%m-%d_%H-%M-%S'; }
log() { echo "[$(timestamp)] $*"; }
die() { log "FATAL: $*"; exit 1; }

command -v claude >/dev/null || die "claude CLI required"
command -v git >/dev/null || die "git required"

# Detect JSON parser: prefer jq, fall back to python3
HAS_JQ=false
command -v jq >/dev/null 2>&1 && HAS_JQ=true
if [ "$HAS_JQ" = false ]; then
  command -v python3 >/dev/null 2>&1 || die "jq or python3 required for JSON parsing"
fi

mkdir -p "$LOG_DIR"
`;
}

function validateImproveOptions(options: ImproveScriptOptions): void {
  if (!Number.isInteger(options.maxIters) || options.maxIters <= 0) {
    throw new Error(`Invalid maxIters: must be a positive integer, got ${options.maxIters}`);
  }
  if (!Number.isInteger(options.timeBudget) || options.timeBudget < 0) {
    throw new Error(`Invalid timeBudget: must be a non-negative integer, got ${options.timeBudget}`);
  }
  if (!MODEL_PATTERN.test(options.model)) {
    throw new Error(`Invalid model "${options.model}": must match ${MODEL_PATTERN}`);
  }
  if (options.topics) {
    for (const topic of options.topics) {
      if (!TOPIC_NAME_PATTERN.test(topic)) {
        throw new Error(`Invalid topic "${topic}": must match ${TOPIC_NAME_PATTERN}`);
      }
    }
  }
}

/**
 * Generate a bash script that autonomously improves the codebase using improve/*.md programs.
 */
export function generateImproveScript(options: ImproveScriptOptions): string {
  validateImproveOptions(options);

  const topicFilter = options.topics?.join(' ') ?? '';
  const timestamp = new Date().toISOString();

  return buildImproveScriptHeader(timestamp, options.maxIters, options.timeBudget, options.model, topicFilter)
    + buildTopicDiscovery()
    + buildImprovePrompt()
    + buildStreamExtractor()
    + buildImproveMarkerDetection()
    + buildImproveObservability()
    + buildImproveMainLoop({ maxIters: options.maxIters, timeBudget: options.timeBudget });
}

async function handleImprove(cmd: Command, options: ImproveOptions): Promise<void> {
  void cmd;

  const maxIters = Number(options.maxIters ?? 5);
  if (!Number.isInteger(maxIters) || maxIters <= 0) {
    out.error(`Invalid --max-iters: must be a positive integer, got "${options.maxIters}"`);
    process.exitCode = 1;
    return;
  }

  const timeBudget = Number(options.timeBudget ?? 0);
  if (!Number.isInteger(timeBudget) || timeBudget < 0) {
    out.error(`Invalid --time-budget: must be a non-negative integer, got "${options.timeBudget}"`);
    process.exitCode = 1;
    return;
  }

  const scriptOptions: ImproveScriptOptions = {
    topics: options.topics,
    maxIters,
    timeBudget,
    model: options.model ?? DEFAULT_MODEL,
  };

  // Dry-run: validate and print plan, don't write file
  if (options.dryRun) {
    try {
      validateImproveOptions(scriptOptions);
    } catch (err) {
      out.error((err as Error).message);
      process.exitCode = 1;
      return;
    }
    out.info('Dry run - improvement loop plan:');
    out.info(`  Topics: ${scriptOptions.topics?.join(', ') ?? '(all improve/*.md)'}`);
    out.info(`  Max iterations per topic: ${scriptOptions.maxIters}`);
    out.info(`  Time budget: ${scriptOptions.timeBudget === 0 ? 'unlimited' : `${scriptOptions.timeBudget}s`}`);
    out.info(`  Model: ${scriptOptions.model}`);
    // Check for improve/*.md files (informational)
    if (existsSync('improve')) {
      out.info('  improve/ directory exists');
    } else {
      out.warn('  improve/ directory not found - create it with improve/*.md files');
    }
    return;
  }

  const outputPath = resolve(options.output ?? './improvement-loop.sh');

  if (existsSync(outputPath) && !options.force) {
    out.error(`File already exists: ${outputPath}`);
    out.info('Use --force to overwrite');
    process.exitCode = 1;
    return;
  }

  let script: string;
  try {
    script = generateImproveScript(scriptOptions);
  } catch (err) {
    out.error((err as Error).message);
    process.exitCode = 1;
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, script, 'utf-8');
  await chmod(outputPath, 0o755);

  out.success(`Generated improvement loop script: ${outputPath}`);
  out.info('Run it with: ' + outputPath);
  out.info('Preview with: IMPROVE_DRY_RUN=1 ' + outputPath);
}

async function handleImproveInit(cmd: Command): Promise<void> {
  void cmd;
  out.info('Create improve/*.md files to define improvement programs.');
  out.info('Each .md file becomes a "topic" the improvement loop will iterate on.');
  out.info('');
  out.info('Example: improve/linting.md');
  out.info('  Describes how to find and fix lint issues in the codebase.');
  out.info('');
  out.info('Then run: ca improve');
}

/**
 * Register improve commands on the program.
 */
export function registerImproveCommands(program: Command): void {
  const improveCmd = program
    .command('improve')
    .description('Generate improvement loop script')
    .option('--topics <names...>', 'Specific topics to process')
    .option('-o, --output <path>', 'Output script path', './improvement-loop.sh')
    .option('--max-iters <n>', 'Max iterations per topic', '5')
    .option('--time-budget <seconds>', 'Total time budget, 0=unlimited', '0')
    .option('--model <model>', 'Claude model to use', DEFAULT_MODEL)
    .option('--force', 'Overwrite existing script')
    .option('--dry-run', 'Validate and print plan without generating')
    .action(async function (this: Command, options: ImproveOptions) {
      await handleImprove(this, options);
    });

  improveCmd
    .command('init')
    .description('Print guidance about creating improve/*.md files')
    .action(async function (this: Command) {
      await handleImproveInit(this);
    });
}
