/**
 * Loop command: generate infinity loop script for autonomous epic processing.
 *
 * Generates a bash script that iterates over beads epics,
 * spawning Claude Code sessions to implement each one.
 */

import { existsSync } from 'node:fs';
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import type { Command } from 'commander';

import {
  buildEpicSelector,
  buildMainLoop,
  buildMarkerDetection,
  buildObservability,
  buildPromptFunction,
  buildStreamExtractor,
} from './loop-templates.js';
import { out } from './shared.js';

/** Safe pattern for epic IDs in loop scripts: extends cli-utils EPIC_ID_PATTERN with dots for version-like IDs */
const LOOP_EPIC_ID_PATTERN = /^[a-zA-Z0-9_.-]+$/;

/** Safe pattern for model names: alphanumeric, hyphens, underscores, dots, colons */
const MODEL_PATTERN = /^[a-zA-Z0-9_.:/-]+$/;

export interface LoopScriptOptions {
  epics?: string[];
  maxRetries: number;
  model: string;
}

interface LoopOptions {
  epics?: string[];
  output?: string;
  maxRetries?: string;
  model?: string;
  force?: boolean;
}

function buildScriptHeader(timestamp: string, maxRetries: number, model: string, epicIds: string): string {
  return `#!/usr/bin/env bash
# Infinity Loop - Generated by: ca loop
# Date: ${timestamp}
# Autonomously processes beads epics via Claude Code sessions.
#
# Usage:
#   ./infinity-loop.sh
#   LOOP_DRY_RUN=1 ./infinity-loop.sh  # Preview without executing

set -euo pipefail

# Config
MAX_RETRIES=${maxRetries}
MODEL="${model}"
EPIC_IDS="${epicIds}"
LOG_DIR="agent_logs"

# Helpers
timestamp() { date '+%Y-%m-%d_%H-%M-%S'; }
log() { echo "[$(timestamp)] $*"; }
die() { log "FATAL: $*"; exit 1; }

command -v claude >/dev/null || die "claude CLI required"
command -v bd >/dev/null || die "bd (beads) CLI required"

# Detect JSON parser: prefer jq, fall back to python3
HAS_JQ=false
command -v jq >/dev/null 2>&1 && HAS_JQ=true
if [ "$HAS_JQ" = false ]; then
  command -v python3 >/dev/null 2>&1 || die "jq or python3 required for JSON parsing"
fi

# parse_json() - extract a value from JSON stdin
# Uses jq (primary) with python3 fallback
# Auto-unwraps single-element arrays (bd show --json returns [...])
# Usage: echo '[{"status":"open"}]' | parse_json '.status'
parse_json() {
  local filter="$1"
  if [ "$HAS_JQ" = true ]; then
    jq -r "if type == \\"array\\" then .[0] else . end | $filter"
  else
    python3 -c "
import sys, json
data = json.load(sys.stdin)
if isinstance(data, list):
    data = data[0] if data else {}
f = '$filter'.strip('.')
parts = [p for p in f.split('.') if p]
v = data
try:
    for p in parts:
        v = v[p]
except (KeyError, IndexError, TypeError):
    v = None
print('' if v is None else v)
"
  fi
}

mkdir -p "$LOG_DIR"
` + buildEpicSelector() + buildPromptFunction();
}

function validateOptions(options: LoopScriptOptions): void {
  if (!Number.isInteger(options.maxRetries) || options.maxRetries < 0) {
    throw new Error(`Invalid maxRetries: must be a non-negative integer, got ${options.maxRetries}`);
  }
  if (!MODEL_PATTERN.test(options.model)) {
    throw new Error(`Invalid model "${options.model}": must match ${MODEL_PATTERN}`);
  }
  if (options.epics) {
    for (const id of options.epics) {
      if (!LOOP_EPIC_ID_PATTERN.test(id)) {
        throw new Error(`Invalid epic ID "${id}": must match ${LOOP_EPIC_ID_PATTERN}`);
      }
    }
  }
}

/**
 * Generate a bash script that autonomously processes beads epics.
 */
export function generateLoopScript(options: LoopScriptOptions): string {
  validateOptions(options);

  const epicIds = options.epics?.join(' ') ?? '';
  const timestamp = new Date().toISOString();

  return buildScriptHeader(timestamp, options.maxRetries, options.model, epicIds)
    + buildStreamExtractor()
    + buildMarkerDetection()
    + buildObservability()
    + buildMainLoop();
}

async function handleLoop(cmd: Command, options: LoopOptions): Promise<void> {
  void cmd;

  const outputPath = resolve(options.output ?? './infinity-loop.sh');

  if (existsSync(outputPath) && !options.force) {
    out.error(`File already exists: ${outputPath}`);
    out.info('Use --force to overwrite');
    process.exitCode = 1;
    return;
  }

  const maxRetries = Number(options.maxRetries ?? 1);
  if (!Number.isInteger(maxRetries) || maxRetries < 0) {
    out.error(`Invalid --max-retries: must be a non-negative integer, got "${options.maxRetries}"`);
    process.exitCode = 1;
    return;
  }

  let script: string;
  try {
    script = generateLoopScript({
      epics: options.epics,
      maxRetries,
      model: options.model ?? 'claude-opus-4-6',
    });
  } catch (err) {
    out.error((err as Error).message);
    process.exitCode = 1;
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, script, 'utf-8');
  await chmod(outputPath, 0o755);

  out.success(`Generated infinity loop script: ${outputPath}`);
  out.info('Run it with: ' + outputPath);
  out.info('Preview with: LOOP_DRY_RUN=1 ' + outputPath);
}

/**
 * Register loop commands on the program.
 */
export function registerLoopCommands(program: Command): void {
  program
    .command('loop')
    .description('Generate infinity loop script for epic tasks')
    .option('--epics <ids...>', 'Specific epic IDs to process')
    .option('-o, --output <path>', 'Output script path', './infinity-loop.sh')
    .option('--max-retries <n>', 'Max retries per epic on failure', '1')
    .option('--model <model>', 'Claude model to use', 'claude-opus-4-6')
    .option('--force', 'Overwrite existing script')
    .action(async function (this: Command, options: LoopOptions) {
      await handleLoop(this, options);
    });
}
