/**
 * Loop command: generate infinity loop script for autonomous epic processing.
 *
 * Generates a bash script that iterates over beads epics,
 * spawning Claude Code sessions to implement each one.
 */

import { existsSync } from 'node:fs';
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import type { Command } from 'commander';

import { out } from './shared.js';

// ============================================================================
// Constants
// ============================================================================

/** Safe pattern for epic IDs in loop scripts: extends cli-utils EPIC_ID_PATTERN with dots for version-like IDs */
const LOOP_EPIC_ID_PATTERN = /^[a-zA-Z0-9_.-]+$/;

/** Safe pattern for model names: alphanumeric, hyphens, underscores, dots, colons */
const MODEL_PATTERN = /^[a-zA-Z0-9_.:/-]+$/;

// ============================================================================
// Types
// ============================================================================

export interface LoopScriptOptions {
  epics?: string[];
  maxRetries: number;
  model: string;
}

interface LoopOptions {
  epics?: string[];
  output?: string;
  maxRetries?: string;
  model?: string;
  force?: boolean;
}

// ============================================================================
// Script Generation
// ============================================================================

function buildScriptHeader(timestamp: string, maxRetries: number, model: string, epicIds: string): string {
  return `#!/usr/bin/env bash
# Infinity Loop - Generated by: ca loop
# Date: ${timestamp}
# Autonomously processes beads epics via Claude Code sessions.
#
# Usage:
#   ./infinity-loop.sh
#   LOOP_DRY_RUN=1 ./infinity-loop.sh  # Preview without executing

set -euo pipefail

# Config
MAX_RETRIES=${maxRetries}
MODEL="${model}"
EPIC_IDS="${epicIds}"
LOG_DIR="agent_logs"

# Helpers
timestamp() { date '+%Y-%m-%d_%H-%M-%S'; }
log() { echo "[$(timestamp)] $*"; }
die() { log "FATAL: $*"; exit 1; }

command -v claude >/dev/null || die "claude CLI required"
command -v bd >/dev/null || die "bd (beads) CLI required"

# Detect JSON parser: prefer jq, fall back to python3
HAS_JQ=false
command -v jq >/dev/null 2>&1 && HAS_JQ=true
if [ "$HAS_JQ" = false ]; then
  command -v python3 >/dev/null 2>&1 || die "jq or python3 required for JSON parsing"
fi

# parse_json() - extract a value from JSON stdin
# Uses jq (primary) with python3 fallback
# Auto-unwraps single-element arrays (bd show --json returns [...])
# Usage: echo '[{"status":"open"}]' | parse_json '.status'
parse_json() {
  local filter="$1"
  if [ "$HAS_JQ" = true ]; then
    jq -r "if type == \\"array\\" then .[0] else . end | $filter"
  else
    python3 -c "
import sys, json
data = json.load(sys.stdin)
if isinstance(data, list):
    data = data[0] if data else {}
f = '$filter'.strip('.')
parts = [p for p in f.split('.') if p]
v = data
try:
    for p in parts:
        v = v[p]
except (KeyError, IndexError, TypeError):
    v = None
print('' if v is None else v)
"
  fi
}

mkdir -p "$LOG_DIR"
` + buildEpicSelector() + buildPromptFunction();
}

function buildEpicSelector(): string {
  return `
get_next_epic() {
  if [ -n "$EPIC_IDS" ]; then
    # From explicit list, find first still-open epic not yet processed
    for epic_id in $EPIC_IDS; do
      case " $PROCESSED " in *" $epic_id "*) continue ;; esac
      local status
      status=$(bd show "$epic_id" --json 2>/dev/null | parse_json '.status' 2>/dev/null || echo "")
      if [ "$status" = "open" ]; then
        echo "$epic_id"
        return 0
      fi
    done
    return 1
  else
    # Dynamic: get next ready epic from dependency graph, filtering processed
    local epic_id
    if [ "$HAS_JQ" = true ]; then
      epic_id=$(bd list --type=epic --ready --json --limit=10 2>/dev/null | jq -r '.[].id' 2>/dev/null | while read -r id; do
        case " $PROCESSED " in *" $id "*) continue ;; esac
        echo "$id"
        break
      done)
    else
      epic_id=$(bd list --type=epic --ready --json --limit=10 2>/dev/null | python3 -c "
import sys, json
processed = set('$PROCESSED'.split())
items = json.load(sys.stdin)
for item in items:
    if item['id'] not in processed:
        print(item['id'])
        break" 2>/dev/null || echo "")
    fi
    if [ -z "$epic_id" ]; then
      return 1
    fi
    echo "$epic_id"
    return 0
  fi
}
`;
}

function buildPromptFunction(): string {
  return `
build_prompt() {
  local epic_id="$1"
  cat <<'PROMPT_HEADER'
You are running in an autonomous infinity loop. Your task is to fully implement a beads epic.

## Step 1: Load context
Run these commands to prime your session:
PROMPT_HEADER
  cat <<PROMPT_BODY
\\\`\\\`\\\`bash
npx ca load-session
bd show $epic_id
\\\`\\\`\\\`

Read the epic details carefully. Understand scope, acceptance criteria, and sub-tasks.

## Step 2: Execute the workflow
Run the full compound workflow for this epic, starting from the plan phase
(brainstorm is already done -- the epic exists):

/compound:lfg from plan -- Epic: $epic_id

Work through all phases: plan, work, review, compound.

## Step 3: On completion
When all work is done and tests pass:
1. Close the epic: \`bd close $epic_id\`
2. Sync beads: \`bd sync\`
3. Commit and push all changes
4. Output this exact marker on its own line:

EPIC_COMPLETE

## Step 4: On failure
If you cannot complete the epic after reasonable effort:
1. Add a note: \`bd update $epic_id --notes "Loop failed: <reason>"\`
2. Output this exact marker on its own line:

EPIC_FAILED

## Step 5: On human required
If you hit a blocker that REQUIRES human action (account creation, API keys,
external service setup, design decisions you cannot make, etc.):
1. Add a note: \`bd update $epic_id --notes "Human required: <reason>"\`
2. Output this exact marker followed by a short reason on the SAME line:

HUMAN_REQUIRED: <reason>

Example: HUMAN_REQUIRED: Need AWS credentials configured in .env

## Rules
- Do NOT ask questions -- there is no human. Make reasonable decisions.
- Do NOT stop early -- complete the full workflow.
- If tests fail, fix them. Retry up to 3 times before declaring failure.
- Use HUMAN_REQUIRED only for true blockers that no amount of retrying can solve.
- Commit incrementally as you make progress.
PROMPT_BODY
}`;
}

function buildStreamExtractor(): string {
  return `
# extract_text() - Extract assistant text from stream-json events
# Reads JSONL from stdin, outputs plain text lines for marker detection
extract_text() {
  if [ "$HAS_JQ" = true ]; then
    jq -j --unbuffered '
      select(.type == "content_block_delta" and .delta.type == "text_delta") |
      .delta.text // empty
    ' 2>/dev/null || { echo "WARN: extract_text parser failed" >&2; }
  else
    python3 -c "
import sys, json
for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    try:
        obj = json.loads(line)
        if obj.get('type') == 'content_block_delta' and obj.get('delta', {}).get('type') == 'text_delta':
            text = obj['delta'].get('text', '')
            if text:
                print(text, end='', flush=True)
    except (json.JSONDecodeError, KeyError):
        pass
" 2>/dev/null || { echo "WARN: extract_text parser failed" >&2; }
  fi
}
`;
}

function buildMainLoop(): string {
  return `
# Main loop
COMPLETED=0
FAILED=0
SKIPPED=0
PROCESSED=""

log "Infinity loop starting"
log "Config: max_retries=$MAX_RETRIES model=$MODEL"
[ -n "$EPIC_IDS" ] && log "Targeting epics: $EPIC_IDS" || log "Targeting: all ready epics"

while true; do
  EPIC_ID=$(get_next_epic) || break

  log "Processing epic: $EPIC_ID"

  ATTEMPT=0
  SUCCESS=false

  while [ $ATTEMPT -le $MAX_RETRIES ]; do
    ATTEMPT=$((ATTEMPT + 1))
    TS=$(timestamp)
    LOGFILE="$LOG_DIR/loop_$EPIC_ID-$TS.log"
    TRACEFILE="$LOG_DIR/trace_$EPIC_ID-$TS.jsonl"

    # Update .latest symlink for ca watch (before claude invocation so watch can discover it)
    ln -sf "$(basename "$TRACEFILE")" "$LOG_DIR/.latest"

    log "Attempt $ATTEMPT/$((MAX_RETRIES + 1)) for $EPIC_ID (log: $LOGFILE)"

    if [ -n "\${LOOP_DRY_RUN:-}" ]; then
      log "[DRY RUN] Would run claude session for $EPIC_ID"
      SUCCESS=true
      break
    fi

    PROMPT=$(build_prompt "$EPIC_ID")

    # Two-scope logging: stream-json to trace JSONL, extracted text to macro log
    claude --dangerously-skip-permissions \\
           --model "$MODEL" \\
           --output-format stream-json \\
           --include-partial-messages \\
           -p "$PROMPT" \\
           2>"$LOGFILE.stderr" | tee "$TRACEFILE" | extract_text > "$LOGFILE" || true

    # Append stderr to macro log
    [ -f "$LOGFILE.stderr" ] && cat "$LOGFILE.stderr" >> "$LOGFILE" && rm -f "$LOGFILE.stderr"

    if grep -q "^EPIC_COMPLETE$" "$LOGFILE"; then
      log "Epic $EPIC_ID completed successfully"
      SUCCESS=true
      break
    elif grep -q "^HUMAN_REQUIRED:" "$LOGFILE"; then
      REASON=$(grep "^HUMAN_REQUIRED:" "$LOGFILE" | head -1 | sed 's/^HUMAN_REQUIRED: *//')
      log "Epic $EPIC_ID needs human action: $REASON"
      bd update "$EPIC_ID" --notes "Human required: $REASON" 2>/dev/null || true
      SKIPPED=$((SKIPPED + 1))
      SUCCESS=skip
      break
    elif grep -q "^EPIC_FAILED$" "$LOGFILE"; then
      log "Epic $EPIC_ID reported failure (attempt $ATTEMPT)"
    else
      log "Epic $EPIC_ID session ended without marker (attempt $ATTEMPT)"
    fi

    if [ $ATTEMPT -le $MAX_RETRIES ]; then
      log "Retrying $EPIC_ID..."
      sleep 5
    fi
  done

  if [ "$SUCCESS" = true ]; then
    COMPLETED=$((COMPLETED + 1))
    log "Epic $EPIC_ID done. Completed so far: $COMPLETED"
  elif [ "$SUCCESS" = skip ]; then
    log "Epic $EPIC_ID skipped (human required). Continuing."
  else
    FAILED=$((FAILED + 1))
    log "Epic $EPIC_ID failed after $((MAX_RETRIES + 1)) attempts. Stopping loop."
    PROCESSED="$PROCESSED $EPIC_ID"
    break
  fi

  PROCESSED="$PROCESSED $EPIC_ID"
done

log "Loop finished. Completed: $COMPLETED, Failed: $FAILED, Skipped: $SKIPPED"
[ $FAILED -eq 0 ] && exit 0 || exit 1`;
}

/**
 * Validate loop script options before generation.
 */
function validateOptions(options: LoopScriptOptions): void {
  if (!Number.isInteger(options.maxRetries) || options.maxRetries < 0) {
    throw new Error(`Invalid maxRetries: must be a non-negative integer, got ${options.maxRetries}`);
  }
  if (!MODEL_PATTERN.test(options.model)) {
    throw new Error(`Invalid model "${options.model}": must match ${MODEL_PATTERN}`);
  }
  if (options.epics) {
    for (const id of options.epics) {
      if (!LOOP_EPIC_ID_PATTERN.test(id)) {
        throw new Error(`Invalid epic ID "${id}": must match ${LOOP_EPIC_ID_PATTERN}`);
      }
    }
  }
}

/**
 * Generate a bash script that autonomously processes beads epics.
 */
export function generateLoopScript(options: LoopScriptOptions): string {
  validateOptions(options);

  const epicIds = options.epics?.join(' ') ?? '';
  const timestamp = new Date().toISOString();

  return buildScriptHeader(timestamp, options.maxRetries, options.model, epicIds)
    + buildStreamExtractor()
    + buildMainLoop();
}

// ============================================================================
// Command Handler
// ============================================================================

async function handleLoop(cmd: Command, options: LoopOptions): Promise<void> {
  // Suppress unused parameter warning -- cmd reserved for future use
  void cmd;

  const outputPath = resolve(options.output ?? './infinity-loop.sh');

  if (existsSync(outputPath) && !options.force) {
    out.error(`File already exists: ${outputPath}`);
    out.info('Use --force to overwrite');
    process.exitCode = 1;
    return;
  }

  const maxRetries = Number(options.maxRetries ?? 1);
  if (!Number.isInteger(maxRetries) || maxRetries < 0) {
    out.error(`Invalid --max-retries: must be a non-negative integer, got "${options.maxRetries}"`);
    process.exitCode = 1;
    return;
  }

  let script: string;
  try {
    script = generateLoopScript({
      epics: options.epics,
      maxRetries,
      model: options.model ?? 'claude-opus-4-6',
    });
  } catch (err) {
    out.error((err as Error).message);
    process.exitCode = 1;
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, script, 'utf-8');
  await chmod(outputPath, 0o755);

  out.success(`Generated infinity loop script: ${outputPath}`);
  out.info('Run it with: ' + outputPath);
  out.info('Preview with: LOOP_DRY_RUN=1 ' + outputPath);
}

// ============================================================================
// Command Registration
// ============================================================================

/**
 * Register loop commands on the program.
 */
export function registerLoopCommands(program: Command): void {
  program
    .command('loop')
    .description('Generate infinity loop script for epic tasks')
    .option('--epics <ids...>', 'Specific epic IDs to process')
    .option('-o, --output <path>', 'Output script path', './infinity-loop.sh')
    .option('--max-retries <n>', 'Max retries per epic on failure', '1')
    .option('--model <model>', 'Claude model to use', 'claude-opus-4-6')
    .option('--force', 'Overwrite existing script')
    .action(async function (this: Command, options: LoopOptions) {
      await handleLoop(this, options);
    });
}
