/**
 * Loop command: generate infinity loop script for autonomous epic processing.
 *
 * Generates a bash script that iterates over beads epics,
 * spawning Claude Code sessions to implement each one.
 */

import { existsSync } from 'node:fs';
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import type { Command } from 'commander';

import {
  buildEpicSelector,
  buildMainLoop,
  buildMarkerDetection,
  buildMemorySafety,
  buildObservability,
  buildPromptFunction,
  buildStreamExtractor,
} from './loop-templates.js';
import {
  buildReviewConfig,
  buildReviewerDetection,
  buildSessionIdManagement,
  buildReviewPrompt,
  buildSpawnReviewers,
  buildImplementerPhase,
  buildReviewLoop,
} from './loop-review-templates.js';
import {
  buildTopicDiscovery,
  buildImprovePrompt,
  buildImproveMarkerDetection,
  buildImproveObservability,
  buildImproveMainLoop,
} from './improve-templates.js';
import type { ImproveMainLoopOptions } from './improve-templates.js';
import { VALID_LOOP_REVIEWERS } from '../config/index.js';
import { DEFAULT_LOOP_MODEL, MODEL_PATTERN, out } from './shared.js';

/** Safe pattern for epic IDs in loop scripts: extends cli-utils EPIC_ID_PATTERN with dots for version-like IDs */
export const LOOP_EPIC_ID_PATTERN = /^[a-zA-Z0-9_.-]+$/;

export interface LoopScriptOptions {
  epics?: string[];
  maxRetries: number;
  model: string;
  reviewers?: string[];
  maxReviewCycles?: number;
  reviewBlocking?: boolean;
  reviewModel?: string;
  reviewEvery?: number;
  improve?: ImproveMainLoopOptions;
}

interface LoopOptions {
  epics?: string[];
  output?: string;
  maxRetries?: string;
  model?: string;
  force?: boolean;
  reviewers?: string[];
  reviewEvery?: string;
  maxReviewCycles?: string;
  reviewBlocking?: boolean;
  reviewModel?: string;
  improve?: boolean;
  improveMaxIters?: string;
  improveTimeBudget?: string;
}

function buildScriptHeader(timestamp: string, maxRetries: number, model: string, epicIds: string): string {
  return `#!/usr/bin/env bash
# Infinity Loop - Generated by: ca loop
# Date: ${timestamp}
# Autonomously processes beads epics via Claude Code sessions.
#
# Usage:
#   ./infinity-loop.sh
#   LOOP_DRY_RUN=1 ./infinity-loop.sh  # Preview without executing

set -euo pipefail

# Crash handler: log WHY we died and update status file
_loop_cleanup() {
  local exit_code=$?
  if [ $exit_code -ne 0 ]; then
    log "CRASH: Script exited with code $exit_code at line \${BASH_LINENO[0]:-unknown}"
    echo "{\\"status\\":\\"crashed\\",\\"exit_code\\":$exit_code,\\"timestamp\\":\\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\\",\\"line\\":\\"\${BASH_LINENO[0]:-unknown}\\"}" > "\${LOG_DIR:-.}/.loop-status.json" 2>/dev/null || true
  fi
}
trap _loop_cleanup EXIT

# Config
MAX_RETRIES=${maxRetries}
MODEL="${model}"
EPIC_IDS="${epicIds}"
LOG_DIR="agent_logs"

# Helpers
timestamp() { date '+%Y-%m-%d_%H-%M-%S'; }
log() { echo "[$(timestamp)] $*"; }
die() { log "FATAL: $*"; exit 1; }

command -v claude >/dev/null || die "claude CLI required"
command -v bd >/dev/null || die "bd (beads) CLI required"

# Detect JSON parser: prefer jq, fall back to python3
HAS_JQ=false
command -v jq >/dev/null 2>&1 && HAS_JQ=true
if [ "$HAS_JQ" = false ]; then
  command -v python3 >/dev/null 2>&1 || die "jq or python3 required for JSON parsing"
fi

# parse_json() - extract a value from JSON stdin
# Uses jq (primary) with python3 fallback
# Auto-unwraps single-element arrays (bd show --json returns [...])
# Usage: echo '[{"status":"open"}]' | parse_json '.status'
parse_json() {
  local filter="$1"
  if [ "$HAS_JQ" = true ]; then
    jq -r "if type == \\"array\\" then .[0] else . end | $filter"
  else
    python3 -c "
import sys, json
data = json.load(sys.stdin)
if isinstance(data, list):
    data = data[0] if data else {}
f = '$filter'.strip('.')
parts = [p for p in f.split('.') if p]
v = data
try:
    for p in parts:
        v = v[p]
except (KeyError, IndexError, TypeError):
    v = None
print('' if v is None else v)
"
  fi
}

mkdir -p "$LOG_DIR"
` + buildEpicSelector() + buildPromptFunction();
}

function validateOptions(options: LoopScriptOptions): void {
  if (!Number.isInteger(options.maxRetries) || options.maxRetries < 0) {
    throw new Error(`Invalid maxRetries: must be a non-negative integer, got ${options.maxRetries}`);
  }
  if (!MODEL_PATTERN.test(options.model)) {
    throw new Error(`Invalid model "${options.model}": must match ${MODEL_PATTERN}`);
  }
  if (options.epics) {
    for (const id of options.epics) {
      if (!LOOP_EPIC_ID_PATTERN.test(id)) {
        throw new Error(`Invalid epic ID "${id}": must match ${LOOP_EPIC_ID_PATTERN}`);
      }
    }
  }
  if (options.reviewers) {
    for (const name of options.reviewers) {
      if (!(VALID_LOOP_REVIEWERS as readonly string[]).includes(name)) {
        throw new Error(`Invalid reviewer "${name}". Valid: ${VALID_LOOP_REVIEWERS.join(', ')}`);
      }
    }
    if (options.reviewModel && !MODEL_PATTERN.test(options.reviewModel)) {
      throw new Error(`Invalid review model "${options.reviewModel}": must match ${MODEL_PATTERN}`);
    }
    if (options.reviewEvery !== undefined && (!Number.isInteger(options.reviewEvery) || options.reviewEvery < 0)) {
      throw new Error(`Invalid reviewEvery: must be a non-negative integer, got ${options.reviewEvery}`);
    }
    if (options.maxReviewCycles !== undefined && (!Number.isInteger(options.maxReviewCycles) || options.maxReviewCycles < 1)) {
      throw new Error(`Invalid maxReviewCycles: must be a positive integer, got ${options.maxReviewCycles}`);
    }
  }
  if (options.improve) {
    if (!Number.isInteger(options.improve.maxIters) || options.improve.maxIters <= 0) {
      throw new Error(`Invalid improve maxIters: must be a positive integer, got ${options.improve.maxIters}`);
    }
    if (!Number.isInteger(options.improve.timeBudget) || options.improve.timeBudget < 0) {
      throw new Error(`Invalid improve timeBudget: must be a non-negative integer, got ${options.improve.timeBudget}`);
    }
  }
}

/**
 * Generate a bash script that autonomously processes beads epics.
 */
export function generateLoopScript(options: LoopScriptOptions): string {
  validateOptions(options);

  const epicIds = options.epics?.join(' ') ?? '';
  const timestamp = new Date().toISOString();
  const hasReview = options.reviewers && options.reviewers.length > 0;

  let script = buildScriptHeader(timestamp, options.maxRetries, options.model, epicIds)
    + buildMemorySafety()
    + buildStreamExtractor()
    + buildMarkerDetection()
    + buildObservability();

  if (hasReview) {
    script += buildReviewConfig({
      reviewers: options.reviewers!,
      maxReviewCycles: options.maxReviewCycles ?? 3,
      reviewBlocking: options.reviewBlocking ?? false,
      reviewModel: options.reviewModel ?? DEFAULT_LOOP_MODEL,
      reviewEvery: options.reviewEvery ?? 0,
    });
    script += buildReviewerDetection();
    script += buildSessionIdManagement();
    script += buildReviewPrompt();
    script += buildSpawnReviewers();
    script += buildImplementerPhase();
    script += buildReviewLoop();
  }

  const hasImprove = !!options.improve;
  script += buildMainLoop(
    hasReview ? { hasReview: true, reviewEvery: options.reviewEvery ?? 0 } : undefined,
    hasImprove, // skipExit when improvement phase follows
  );

  if (options.improve) {
    script += '\n# Improvement phase (runs after epic loop completes successfully)\n';
    script += 'if [ $FAILED -eq 0 ]; then\n';
    script += '  log "Epic loop completed successfully, starting improvement phase"\n';
    script += buildTopicDiscovery();
    script += buildImprovePrompt();
    script += buildImproveMarkerDetection();
    script += buildImproveObservability();
    script += buildImproveMainLoop({ ...options.improve, embedded: true });
    script += '\nfi\n';
    // Final exit: check both loop and improvement results
    script += '[ $FAILED -eq 0 ] && [ "${IMPROVE_RESULT:-0}" -eq 0 ] && exit 0 || exit 1\n';
  }

  return script;
}

async function handleLoop(cmd: Command, options: LoopOptions): Promise<void> {
  void cmd;

  const outputPath = resolve(options.output ?? './infinity-loop.sh');

  if (existsSync(outputPath) && !options.force) {
    out.error(`File already exists: ${outputPath}`);
    out.info('Use --force to overwrite');
    process.exitCode = 1;
    return;
  }

  const maxRetries = Number(options.maxRetries ?? 1);
  if (!Number.isInteger(maxRetries) || maxRetries < 0) {
    out.error(`Invalid --max-retries: must be a non-negative integer, got "${options.maxRetries}"`);
    process.exitCode = 1;
    return;
  }

  const reviewEvery = Number(options.reviewEvery ?? 0);
  const maxReviewCycles = Number(options.maxReviewCycles ?? 3);

  const improveMaxIters = Number(options.improveMaxIters ?? 5);
  const improveTimeBudget = Number(options.improveTimeBudget ?? 0);

  let script: string;
  try {
    script = generateLoopScript({
      epics: options.epics,
      maxRetries,
      model: options.model ?? DEFAULT_LOOP_MODEL,
      reviewers: options.reviewers,
      reviewEvery,
      maxReviewCycles,
      reviewBlocking: options.reviewBlocking,
      reviewModel: options.reviewModel ?? DEFAULT_LOOP_MODEL,
      improve: options.improve ? { maxIters: improveMaxIters, timeBudget: improveTimeBudget } : undefined,
    });
  } catch (err) {
    out.error((err as Error).message);
    process.exitCode = 1;
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, script, 'utf-8');
  await chmod(outputPath, 0o755);

  out.success(`Generated infinity loop script: ${outputPath}`);
  out.info('Run it with: ' + outputPath);
  out.info('Preview with: LOOP_DRY_RUN=1 ' + outputPath);
}

/**
 * Register loop commands on the program.
 */
export function registerLoopCommands(program: Command): void {
  program
    .command('loop')
    .description('Generate infinity loop script for epic tasks')
    .option('--epics <ids...>', 'Specific epic IDs to process')
    .option('-o, --output <path>', 'Output script path', './infinity-loop.sh')
    .option('--max-retries <n>', 'Max retries per epic on failure', '1')
    .option('--model <model>', 'Claude model to use', DEFAULT_LOOP_MODEL)
    .option('--force', 'Overwrite existing script')
    .option('--review-every <n>', 'Review every N completed epics (0=end-only)', '0')
    .option('--reviewers <names...>', 'Reviewers to use (claude-sonnet claude-opus gemini codex)')
    .option('--max-review-cycles <n>', 'Max review/fix iterations', '3')
    .option('--review-blocking', 'Fail loop if review not approved after max cycles')
    .option('--review-model <model>', 'Model for implementer fix sessions', DEFAULT_LOOP_MODEL)
    .option('--improve', 'Run improvement phase after all epics complete')
    .option('--improve-max-iters <n>', 'Max improvement iterations per topic', '5')
    .option('--improve-time-budget <seconds>', 'Total improvement time budget, 0=unlimited', '0')
    .action(async function (this: Command, options: LoopOptions) {
      await handleLoop(this, options);
    });
}
