/**
 * Shared primitives for setup commands.
 * Used by both init.ts and setup-all.ts to avoid duplication.
 */

import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { VERSION } from '../version.js';
import {
  AGENTS_MD_TEMPLATE,
  CLAUDE_MD_REFERENCE,
  CLAUDE_REF_START_MARKER,
  COMPOUND_AGENT_SECTION_HEADER,
  PLUGIN_MANIFEST,
} from './templates.js';
import { AGENT_TEMPLATES, AGENT_ROLE_SKILLS, DOC_TEMPLATES, WORKFLOW_COMMANDS, PHASE_SKILLS, PHASE_SKILL_REFERENCES } from './templates/index.js';

/**
 * @deprecated Kept for backward compatibility with all.ts --update detection.
 * New installs use path-based detection (file inside compound/ = managed).
 */
export const GENERATED_MARKER = '<!-- generated by compound-agent -->\n';

/**
 * Check if AGENTS.md already has the Compound Agent section.
 */
export function hasCompoundAgentSection(content: string): boolean {
  return content.includes(COMPOUND_AGENT_SECTION_HEADER);
}

/**
 * Check if CLAUDE.md already has the Compound Agent reference.
 */
export function hasClaudeMdReference(content: string): boolean {
  return content.includes('Compound Agent') || content.includes(CLAUDE_REF_START_MARKER);
}

/**
 * Create or update AGENTS.md with Compound Agent section.
 */
export async function updateAgentsMd(repoRoot: string): Promise<boolean> {
  const agentsPath = join(repoRoot, 'AGENTS.md');
  let content = '';
  let existed = false;

  if (existsSync(agentsPath)) {
    content = await readFile(agentsPath, 'utf-8');
    existed = true;
    if (hasCompoundAgentSection(content)) {
      return false; // Already has section, no update needed
    }
  }

  // Append the template
  const newContent = existed ? content.trimEnd() + '\n' + AGENTS_MD_TEMPLATE : AGENTS_MD_TEMPLATE.trim() + '\n';
  await writeFile(agentsPath, newContent, 'utf-8');
  return true;
}

/**
 * Ensure CLAUDE.md has a reference to AGENTS.md for Compound Agent workflow.
 * Creates CLAUDE.md if it doesn't exist, appends reference if not present.
 * Uses markers for clean uninstall support.
 */
export async function ensureClaudeMdReference(repoRoot: string): Promise<boolean> {
  const claudeMdPath = join(repoRoot, '.claude', 'CLAUDE.md');

  // Ensure .claude directory exists
  await mkdir(join(repoRoot, '.claude'), { recursive: true });

  if (!existsSync(claudeMdPath)) {
    // Create new CLAUDE.md with reference
    const content = `# Project Instructions
${CLAUDE_MD_REFERENCE}`;
    await writeFile(claudeMdPath, content, 'utf-8');
    return true;
  }

  // File exists - check if reference is already present
  const content = await readFile(claudeMdPath, 'utf-8');
  if (hasClaudeMdReference(content)) {
    return false; // Already has reference
  }

  // Append reference
  const newContent = content.trimEnd() + '\n' + CLAUDE_MD_REFERENCE;
  await writeFile(claudeMdPath, newContent, 'utf-8');
  return true;
}

/**
 * Create plugin.json in .claude/ directory.
 * Idempotent: does not overwrite existing file.
 *
 * @returns true if plugin.json was created
 */
export async function createPluginManifest(repoRoot: string): Promise<boolean> {
  const pluginPath = join(repoRoot, '.claude', 'plugin.json');

  // Ensure .claude directory exists
  await mkdir(join(repoRoot, '.claude'), { recursive: true });

  if (existsSync(pluginPath)) {
    return false; // Already exists
  }

  await writeFile(pluginPath, JSON.stringify(PLUGIN_MANIFEST, null, 2) + '\n', 'utf-8');
  return true;
}


/**
 * Install agent templates to .claude/agents/compound/.
 * Idempotent: does not overwrite existing files.
 *
 * @returns true if any agent templates were created
 */
export async function installAgentTemplates(repoRoot: string): Promise<boolean> {
  const agentsDir = join(repoRoot, '.claude', 'agents', 'compound');
  await mkdir(agentsDir, { recursive: true });

  let created = false;
  for (const [filename, content] of Object.entries(AGENT_TEMPLATES)) {
    const filePath = join(agentsDir, filename);
    if (!existsSync(filePath)) {
      await writeFile(filePath, content, 'utf-8');
      created = true;
    }
  }
  return created;
}

/**
 * Install workflow commands to .claude/commands/compound/.
 * Idempotent: does not overwrite existing files.
 *
 * @returns true if any workflow commands were created
 */
export async function installWorkflowCommands(repoRoot: string): Promise<boolean> {
  const commandsDir = join(repoRoot, '.claude', 'commands', 'compound');
  await mkdir(commandsDir, { recursive: true });

  let created = false;
  for (const [filename, content] of Object.entries(WORKFLOW_COMMANDS)) {
    const filePath = join(commandsDir, filename);
    if (!existsSync(filePath)) {
      await writeFile(filePath, content, 'utf-8');
      created = true;
    }
  }
  return created;
}

/**
 * Install phase skill templates to .claude/skills/compound/<phase>/SKILL.md.
 * Idempotent: does not overwrite existing files.
 *
 * @returns true if any skill templates were created
 */
export async function installPhaseSkills(repoRoot: string): Promise<boolean> {
  let created = false;
  for (const [phase, content] of Object.entries(PHASE_SKILLS)) {
    const skillDir = join(repoRoot, '.claude', 'skills', 'compound', phase);
    await mkdir(skillDir, { recursive: true });
    const filePath = join(skillDir, 'SKILL.md');
    if (!existsSync(filePath)) {
      await writeFile(filePath, content, 'utf-8');
      created = true;
    }
  }

  // Install reference files alongside skills
  for (const [relPath, content] of Object.entries(PHASE_SKILL_REFERENCES)) {
    const filePath = join(repoRoot, '.claude', 'skills', 'compound', relPath);
    await mkdir(dirname(filePath), { recursive: true });
    if (!existsSync(filePath)) {
      await writeFile(filePath, content, 'utf-8');
      created = true;
    }
  }

  return created;
}

/**
 * Install agent role skill templates to .claude/skills/compound/agents/<name>/SKILL.md.
 * Idempotent: does not overwrite existing files.
 *
 * @returns true if any agent role skills were created
 */
export async function installAgentRoleSkills(repoRoot: string): Promise<boolean> {
  let created = false;
  for (const [name, content] of Object.entries(AGENT_ROLE_SKILLS)) {
    const skillDir = join(repoRoot, '.claude', 'skills', 'compound', 'agents', name);
    await mkdir(skillDir, { recursive: true });
    const filePath = join(skillDir, 'SKILL.md');
    if (!existsSync(filePath)) {
      await writeFile(filePath, content, 'utf-8');
      created = true;
    }
  }
  return created;
}

/**
 * Install documentation templates to docs/compound/.
 * Idempotent: does not overwrite existing files.
 * Replaces {{VERSION}} placeholder with the actual package version.
 *
 * @returns true if any doc templates were created
 */
export async function installDocTemplates(repoRoot: string): Promise<boolean> {
  const docsDir = join(repoRoot, 'docs', 'compound');
  await mkdir(docsDir, { recursive: true });

  let created = false;
  for (const [filename, template] of Object.entries(DOC_TEMPLATES)) {
    const filePath = join(docsDir, filename);
    if (!existsSync(filePath)) {
      const content = template.replace('{{VERSION}}', VERSION).replace('{{DATE}}', new Date().toISOString().slice(0, 10));
      await writeFile(filePath, content, 'utf-8');
      created = true;
    }
  }
  return created;
}

/**
 * Install research docs from the package's docs/research/ to docs/compound/research/ in the user's project.
 *
 * @param force - When true, overwrites existing files if content differs (used by --update).
 *                When false (default), skips existing files (idempotent fresh install).
 * @returns true if any research docs were created or updated
 */
export async function installResearchDocs(repoRoot: string, options?: { force?: boolean }): Promise<boolean> {
  const force = options?.force ?? false;
  // Resolve the package's docs/research/ directory via import.meta.url
  // In the built bundle, import.meta.url points to dist/cli.js.
  // Go up one level from dist/ to reach the package root.
  const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
  const srcDir = join(pkgRoot, 'docs', 'research');

  if (!existsSync(srcDir)) {
    return false; // Package doesn't include research docs (dev-only)
  }

  const destDir = join(repoRoot, 'docs', 'compound', 'research');
  await mkdir(destDir, { recursive: true });

  let created = false;

  async function copyDir(src: string, dest: string): Promise<void> {
    const entries = await readdir(src, { withFileTypes: true });
    for (const entry of entries) {
      const srcPath = join(src, entry.name);
      const destPath = join(dest, entry.name);
      if (entry.isDirectory()) {
        await mkdir(destPath, { recursive: true });
        await copyDir(srcPath, destPath);
        continue;
      }
      if (!entry.name.endsWith('.md')) continue;
      const exists = existsSync(destPath);
      if (exists && !force) continue;

      let content = await readFile(srcPath, 'utf-8');
      // Rewrite index.md header to note provenance
      if (entry.name === 'index.md') {
        const patched = content.replace(
          /^# .*/m,
          '$&\n\n> Shipped by compound-agent. Source: `docs/research/` in the compound-agent package.',
        );
        content = patched !== content ? patched : `> Shipped by compound-agent.\n\n${content}`;
      }
      // In force mode, skip write if content is unchanged
      if (exists && (await readFile(destPath, 'utf-8')) === content) continue;
      await writeFile(destPath, content, 'utf-8');
      created = true;
    }
  }

  try {
    await copyDir(srcDir, destDir);
  } catch (err) {
    console.error(`Warning: Could not install research docs: ${(err as Error).message}`);
    return false;
  }
  return created;
}

// ============================================================================
// pnpm native build configuration
// ============================================================================

/** Native addon packages that require pnpm onlyBuiltDependencies opt-in. */
const REQUIRED_BUILD_DEPS = ['better-sqlite3', 'node-llama-cpp'];

/** Result of pnpm build config check/update. */
export interface PnpmConfigResult {
  /** Whether this is a pnpm project (pnpm-lock.yaml or packageManager field). */
  isPnpm: boolean;
  /** Whether the config was already correct (no changes needed). */
  alreadyConfigured: boolean;
  /** Package names that were added to onlyBuiltDependencies. */
  added: string[];
}

/**
 * Ensure pnpm projects have onlyBuiltDependencies configured for native addons.
 *
 * pnpm v9+ blocks native addon compilation by default. This function detects
 * pnpm projects (via pnpm-lock.yaml or packageManager field) and adds the
 * required packages to pnpm.onlyBuiltDependencies in the consumer's package.json.
 *
 * Idempotent: does not duplicate entries or overwrite existing config.
 */
export async function ensurePnpmBuildConfig(repoRoot: string): Promise<PnpmConfigResult> {
  const lockPath = join(repoRoot, 'pnpm-lock.yaml');
  const hasLockfile = existsSync(lockPath);
  const pkgPath = join(repoRoot, 'package.json');
  const hasPkgJson = existsSync(pkgPath);

  // Detect pnpm: lockfile OR packageManager field starting with "pnpm"
  if (!hasLockfile) {
    if (!hasPkgJson) {
      return { isPnpm: false, alreadyConfigured: false, added: [] };
    }
    const pkg = readPkgJsonSafe(pkgPath, await readFile(pkgPath, 'utf-8'));
    if (pkg === null) return { isPnpm: false, alreadyConfigured: false, added: [] };
    const pm = typeof pkg.packageManager === 'string' ? pkg.packageManager : '';
    if (!pm.startsWith('pnpm')) {
      return { isPnpm: false, alreadyConfigured: false, added: [] };
    }
    // pnpm detected via packageManager field — fall through to config merge
    return mergePnpmConfig(pkgPath, pkg);
  }

  if (!hasPkgJson) {
    return { isPnpm: true, alreadyConfigured: false, added: [] };
  }

  const pkg = readPkgJsonSafe(pkgPath, await readFile(pkgPath, 'utf-8'));
  if (pkg === null) return { isPnpm: true, alreadyConfigured: false, added: [] };
  return mergePnpmConfig(pkgPath, pkg);
}

function readPkgJsonSafe(pkgPath: string, raw: string): Record<string, unknown> | null {
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    console.error(`Warning: Could not parse ${pkgPath} — skipping pnpm build config.\nFix the JSON syntax and re-run setup.`);
    return null;
  }
}

async function mergePnpmConfig(pkgPath: string, pkg: Record<string, unknown>): Promise<PnpmConfigResult> {
  // Get or create pnpm.onlyBuiltDependencies
  if (!pkg.pnpm || typeof pkg.pnpm !== 'object') {
    pkg.pnpm = {};
  }
  const pnpmConfig = pkg.pnpm as Record<string, unknown>;

  if (!Array.isArray(pnpmConfig.onlyBuiltDependencies)) {
    pnpmConfig.onlyBuiltDependencies = [];
  }
  const existing = pnpmConfig.onlyBuiltDependencies as string[];

  const added: string[] = [];
  for (const dep of REQUIRED_BUILD_DEPS) {
    if (!existing.includes(dep)) {
      existing.push(dep);
      added.push(dep);
    }
  }

  if (added.length === 0) {
    return { isPnpm: true, alreadyConfigured: true, added: [] };
  }

  await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');
  return { isPnpm: true, alreadyConfigured: false, added };
}

// ============================================================================
// SQLite verification + auto-rebuild
// ============================================================================

import { ensureSqliteAvailable, resetSqliteAvailability } from '../memory/storage/index.js';

/** Result of post-setup SQLite verification. */
export interface SqliteVerifyResult {
  /** Whether SQLite (better-sqlite3) is currently loadable. */
  available: boolean;
  /** What action was taken (or attempted). */
  action: 'already_ok' | 'rebuilt' | 'installed_and_rebuilt' | 'failed';
  /** Error message if action is 'failed'. */
  error?: string;
}

/**
 * Try loading SQLite, returning true on success, false on failure.
 */
function trySqliteLoad(): boolean {
  try {
    ensureSqliteAvailable();
    return true;
  } catch {
    return false;
  }
}

/**
 * Verify SQLite availability and attempt auto-rebuild if needed.
 *
 * Strategy:
 *  1. Try ensureSqliteAvailable() — if works, fast path (zero overhead)
 *  2. If non-pnpm: report failure with npm rebuild suggestion
 *  3. If pnpm: try `pnpm rebuild better-sqlite3`, re-check
 *  4. If still fails: try `pnpm install` then rebuild, re-check
 *  5. All attempts fail: report with manual instructions
 *
 * Non-blocking: never throws. Reports result honestly.
 */
export function verifySqlite(repoRoot: string, pnpmConfig: PnpmConfigResult): SqliteVerifyResult {
  // Fast path: already works
  if (trySqliteLoad()) {
    return { available: true, action: 'already_ok' };
  }

  // Non-pnpm: can't auto-fix (npm/yarn build native modules by default)
  if (!pnpmConfig.isPnpm) {
    return {
      available: false,
      action: 'failed',
      error: 'better-sqlite3 failed to load. Run: npm rebuild better-sqlite3',
    };
  }

  // Attempt 1: pnpm rebuild better-sqlite3
  try {
    execFileSync('pnpm', ['rebuild', 'better-sqlite3'], {
      cwd: repoRoot,
      stdio: 'pipe',
      timeout: 60_000,
    });
  } catch {
    // rebuild failed, will try install next
  }

  resetSqliteAvailability();
  if (trySqliteLoad()) {
    return { available: true, action: 'rebuilt' };
  }

  // Attempt 2: pnpm install + rebuild (escalation)
  try {
    execFileSync('pnpm', ['install'], {
      cwd: repoRoot,
      stdio: 'pipe',
      timeout: 120_000,
    });
    execFileSync('pnpm', ['rebuild', 'better-sqlite3'], {
      cwd: repoRoot,
      stdio: 'pipe',
      timeout: 60_000,
    });
  } catch {
    // install or rebuild failed
  }

  resetSqliteAvailability();
  if (trySqliteLoad()) {
    return { available: true, action: 'installed_and_rebuilt' };
  }

  return {
    available: false,
    action: 'failed',
    error: 'Auto-rebuild failed. Run manually: pnpm install && pnpm rebuild better-sqlite3',
  };
}
