/**
 * Tests for the upgrade module.
 * Covers: detectExistingInstall, removeDeprecatedCommands, stripGeneratedHeaders, runUpgrade.
 */

import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';

import {
  detectExistingInstall,
  removeDeprecatedCommands,
  stripGeneratedHeaders,
  runUpgrade,
  type UpgradeResult,
} from './upgrade.js';

let tempDir: string;

beforeEach(async () => {
  tempDir = await mkdtemp(join(tmpdir(), 'upgrade-test-'));
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

describe('detectExistingInstall', () => {
  it('returns true when .claude/lessons/index.jsonl exists', async () => {
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    expect(detectExistingInstall(tempDir)).toBe(true);
  });

  it('returns false when .claude/lessons/index.jsonl does not exist', () => {
    expect(detectExistingInstall(tempDir)).toBe(false);
  });

  it('returns false when .claude/ exists but no lessons', async () => {
    await mkdir(join(tempDir, '.claude'), { recursive: true });

    expect(detectExistingInstall(tempDir)).toBe(false);
  });
});

describe('removeDeprecatedCommands', () => {
  const DEPRECATED = ['search.md', 'list.md', 'show.md', 'stats.md', 'wrong.md'];

  it('removes all 5 deprecated command files from compound/', async () => {
    const commandsDir = join(tempDir, '.claude', 'commands', 'compound');
    await mkdir(commandsDir, { recursive: true });

    for (const f of DEPRECATED) {
      await writeFile(join(commandsDir, f), 'some content', 'utf-8');
    }

    const removed = await removeDeprecatedCommands(tempDir);

    expect(removed.sort()).toEqual(DEPRECATED.sort());
    for (const f of DEPRECATED) {
      expect(existsSync(join(commandsDir, f))).toBe(false);
    }
  });

  it('returns only files that actually existed', async () => {
    const commandsDir = join(tempDir, '.claude', 'commands', 'compound');
    await mkdir(commandsDir, { recursive: true });

    // Only create 2 of the 5
    await writeFile(join(commandsDir, 'search.md'), 'content', 'utf-8');
    await writeFile(join(commandsDir, 'stats.md'), 'content', 'utf-8');

    const removed = await removeDeprecatedCommands(tempDir);

    expect(removed.sort()).toEqual(['search.md', 'stats.md'].sort());
  });

  it('returns empty array when compound/ directory does not exist', async () => {
    const removed = await removeDeprecatedCommands(tempDir);
    expect(removed).toEqual([]);
  });

  it('does NOT remove non-deprecated files in compound/', async () => {
    const commandsDir = join(tempDir, '.claude', 'commands', 'compound');
    await mkdir(commandsDir, { recursive: true });

    await writeFile(join(commandsDir, 'brainstorm.md'), 'keep me', 'utf-8');
    await writeFile(join(commandsDir, 'learn.md'), 'keep me too', 'utf-8');
    await writeFile(join(commandsDir, 'search.md'), 'remove me', 'utf-8');

    await removeDeprecatedCommands(tempDir);

    expect(existsSync(join(commandsDir, 'brainstorm.md'))).toBe(true);
    expect(existsSync(join(commandsDir, 'learn.md'))).toBe(true);
    expect(existsSync(join(commandsDir, 'search.md'))).toBe(false);
  });

  it('NEVER touches root-level .claude/commands/ files', async () => {
    const rootCommandsDir = join(tempDir, '.claude', 'commands');
    await mkdir(rootCommandsDir, { recursive: true });

    await writeFile(join(rootCommandsDir, 'search.md'), 'user command', 'utf-8');

    await removeDeprecatedCommands(tempDir);

    expect(existsSync(join(rootCommandsDir, 'search.md'))).toBe(true);
    const content = await readFile(join(rootCommandsDir, 'search.md'), 'utf-8');
    expect(content).toBe('user command');
  });
});

describe('stripGeneratedHeaders', () => {
  it('strips header from files in commands/compound/', async () => {
    const dir = join(tempDir, '.claude', 'commands', 'compound');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'brainstorm.md'), '<!-- generated by compound-agent -->\ncontent here', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(1);
    const content = await readFile(join(dir, 'brainstorm.md'), 'utf-8');
    expect(content).toBe('content here');
  });

  it('strips header from files in skills/compound/', async () => {
    const dir = join(tempDir, '.claude', 'skills', 'compound', 'brainstorm');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'SKILL.md'), '<!-- generated by compound-agent -->\nskill content', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(1);
    const content = await readFile(join(dir, 'SKILL.md'), 'utf-8');
    expect(content).toBe('skill content');
  });

  it('strips header from files in agents/compound/', async () => {
    const dir = join(tempDir, '.claude', 'agents', 'compound');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'repo-analyst.md'), '<!-- generated by compound-agent -->\nagent content', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(1);
    const content = await readFile(join(dir, 'repo-analyst.md'), 'utf-8');
    expect(content).toBe('agent content');
  });

  it('does NOT strip from files without the header', async () => {
    const dir = join(tempDir, '.claude', 'commands', 'compound');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'custom.md'), 'no header here', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(0);
    const content = await readFile(join(dir, 'custom.md'), 'utf-8');
    expect(content).toBe('no header here');
  });

  it('handles multiple files across all three directories', async () => {
    const cmdDir = join(tempDir, '.claude', 'commands', 'compound');
    const skillDir = join(tempDir, '.claude', 'skills', 'compound', 'work');
    const agentDir = join(tempDir, '.claude', 'agents', 'compound');
    await mkdir(cmdDir, { recursive: true });
    await mkdir(skillDir, { recursive: true });
    await mkdir(agentDir, { recursive: true });

    await writeFile(join(cmdDir, 'a.md'), '<!-- generated by compound-agent -->\na', 'utf-8');
    await writeFile(join(cmdDir, 'b.md'), '<!-- generated by compound-agent -->\nb', 'utf-8');
    await writeFile(join(skillDir, 'SKILL.md'), '<!-- generated by compound-agent -->\nc', 'utf-8');
    await writeFile(join(agentDir, 'x.md'), '<!-- generated by compound-agent -->\nd', 'utf-8');
    await writeFile(join(agentDir, 'y.md'), 'no header', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(4);
  });

  it('returns 0 when no compound/ directories exist', async () => {
    const count = await stripGeneratedHeaders(tempDir);
    expect(count).toBe(0);
  });

  it('handles nested skill directories (skills/compound/agents/<name>/)', async () => {
    const dir = join(tempDir, '.claude', 'skills', 'compound', 'agents', 'test-writer');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'SKILL.md'), '<!-- generated by compound-agent -->\nskill', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(1);
    const content = await readFile(join(dir, 'SKILL.md'), 'utf-8');
    expect(content).toBe('skill');
  });
});

describe('runUpgrade', () => {
  it('returns isUpgrade: false when no existing install', async () => {
    const result = await runUpgrade(tempDir);

    expect(result.isUpgrade).toBe(false);
    expect(result.removedCommands).toEqual([]);
    expect(result.strippedHeaders).toBe(0);
    expect(result.message).toBeDefined();
  });

  it('returns isUpgrade: true when existing install detected', async () => {
    // Create existing install indicator
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    const result = await runUpgrade(tempDir);

    expect(result.isUpgrade).toBe(true);
  });

  it('orchestrates removal of deprecated commands and header stripping', async () => {
    // Set up existing install
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    // Create deprecated commands
    const cmdDir = join(tempDir, '.claude', 'commands', 'compound');
    await mkdir(cmdDir, { recursive: true });
    await writeFile(join(cmdDir, 'search.md'), 'content', 'utf-8');
    await writeFile(join(cmdDir, 'list.md'), 'content', 'utf-8');

    // Create files with headers
    const agentDir = join(tempDir, '.claude', 'agents', 'compound');
    await mkdir(agentDir, { recursive: true });
    await writeFile(join(agentDir, 'repo-analyst.md'), '<!-- generated by compound-agent -->\nagent', 'utf-8');

    const result = await runUpgrade(tempDir);

    expect(result.isUpgrade).toBe(true);
    expect(result.removedCommands.sort()).toEqual(['list.md', 'search.md'].sort());
    expect(result.strippedHeaders).toBe(1);
    expect(result.message).toBeDefined();
  });

  it('provides a summary message', async () => {
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    const result = await runUpgrade(tempDir);

    expect(typeof result.message).toBe('string');
    expect(result.message.length).toBeGreaterThan(0);
  });
});
