/**
 * Upgrade module for cleaning up existing compound-agent installs.
 * Handles: deprecated command removal, generated header stripping.
 */

import { existsSync } from 'node:fs';
import { readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export interface UpgradeResult {
  isUpgrade: boolean;
  removedCommands: string[];
  strippedHeaders: number;
  message: string;
}

const GENERATED_HEADER = '<!-- generated by compound-agent -->\n';

/** CLI wrapper commands deprecated in v1.3. */
const DEPRECATED_COMMANDS = ['search.md', 'list.md', 'show.md', 'stats.md', 'wrong.md'];

/** Detect if this is an existing install (upgrade scenario). */
export function detectExistingInstall(repoRoot: string): boolean {
  return existsSync(join(repoRoot, '.claude', 'lessons', 'index.jsonl'));
}

/** Remove deprecated CLI wrapper command files from .claude/commands/compound/. */
export async function removeDeprecatedCommands(repoRoot: string): Promise<string[]> {
  const commandsDir = join(repoRoot, '.claude', 'commands', 'compound');
  if (!existsSync(commandsDir)) return [];

  const removed: string[] = [];
  for (const filename of DEPRECATED_COMMANDS) {
    const filePath = join(commandsDir, filename);
    if (existsSync(filePath)) {
      await rm(filePath);
      removed.push(filename);
    }
  }
  return removed;
}

/** Strip generated headers from installed files in compound/ dirs. */
export async function stripGeneratedHeaders(repoRoot: string): Promise<number> {
  const dirs = [
    join(repoRoot, '.claude', 'commands', 'compound'),
    join(repoRoot, '.claude', 'skills', 'compound'),
    join(repoRoot, '.claude', 'agents', 'compound'),
  ];

  let count = 0;
  for (const dir of dirs) {
    if (!existsSync(dir)) continue;
    count += await stripHeadersRecursive(dir);
  }
  return count;
}

/** Recursively walk a directory and strip headers from .md files. */
async function stripHeadersRecursive(dir: string): Promise<number> {
  let count = 0;
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      count += await stripHeadersRecursive(fullPath);
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      const content = await readFile(fullPath, 'utf-8');
      if (content.startsWith(GENERATED_HEADER)) {
        await writeFile(fullPath, content.slice(GENERATED_HEADER.length), 'utf-8');
        count++;
      }
    }
  }
  return count;
}

/**
 * Update the version line in docs/compound/HOW_TO_COMPOUND.md during upgrade.
 * Returns true if the file was updated, false if missing or already current.
 */
export async function upgradeDocVersion(repoRoot: string, newVersion: string): Promise<boolean> {
  const docPath = join(repoRoot, 'docs', 'compound', 'HOW_TO_COMPOUND.md');
  if (!existsSync(docPath)) return false;

  const content = await readFile(docPath, 'utf-8');
  const updated = content.replace(/^(version: ")([^"]+)(")/m, `$1${newVersion}$3`);
  if (updated === content) return false;

  await writeFile(docPath, updated, 'utf-8');
  return true;
}

/** Run full upgrade flow. */
export async function runUpgrade(repoRoot: string): Promise<UpgradeResult> {
  const isUpgrade = detectExistingInstall(repoRoot);

  if (!isUpgrade) {
    return {
      isUpgrade: false,
      removedCommands: [],
      strippedHeaders: 0,
      message: 'No existing install detected. Nothing to upgrade.',
    };
  }

  const removedCommands = await removeDeprecatedCommands(repoRoot);
  const strippedHeaders = await stripGeneratedHeaders(repoRoot);

  const parts: string[] = [];
  if (removedCommands.length > 0) {
    parts.push(`Removed ${removedCommands.length} deprecated command(s)`);
  }
  if (strippedHeaders > 0) {
    parts.push(`Stripped headers from ${strippedHeaders} file(s)`);
  }
  const message = parts.length > 0
    ? `Upgrade complete: ${parts.join(', ')}.`
    : 'Upgrade complete: no changes needed.';

  return { isUpgrade, removedCommands, strippedHeaders, message };
}
