/**
 * Upgrade module for cleaning up existing compound-agent installs.
 * Handles: generated header stripping, doc version updates.
 */

import { existsSync } from 'node:fs';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { VERSION } from '../version.js';

export interface UpgradeResult {
  isUpgrade: boolean;
  strippedHeaders: number;
  docVersionUpdated: boolean;
  message: string;
}

const GENERATED_HEADER = '<!-- generated by compound-agent -->\n';

/** Detect if this is an existing install (upgrade scenario). */
export function detectExistingInstall(repoRoot: string): boolean {
  return existsSync(join(repoRoot, '.claude', 'lessons', 'index.jsonl'));
}

/** Strip generated headers from installed files in compound/ dirs. */
export async function stripGeneratedHeaders(repoRoot: string, dryRun = false): Promise<number> {
  const dirs = [
    join(repoRoot, '.claude', 'commands', 'compound'),
    join(repoRoot, '.claude', 'skills', 'compound'),
    join(repoRoot, '.claude', 'agents', 'compound'),
  ];

  let count = 0;
  for (const dir of dirs) {
    if (!existsSync(dir)) continue;
    count += await stripHeadersRecursive(dir, dryRun);
  }
  return count;
}

/** Recursively walk a directory and strip headers from .md files. */
async function stripHeadersRecursive(dir: string, dryRun = false): Promise<number> {
  let count = 0;
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      count += await stripHeadersRecursive(fullPath, dryRun);
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      const content = await readFile(fullPath, 'utf-8');
      if (content.startsWith(GENERATED_HEADER)) {
        if (!dryRun) await writeFile(fullPath, content.slice(GENERATED_HEADER.length), 'utf-8');
        count++;
      }
    }
  }
  return count;
}

/**
 * Update the version line in docs/compound/README.md during upgrade.
 * Returns true if the file was updated, false if missing or already current.
 */
export async function upgradeDocVersion(repoRoot: string, newVersion: string, dryRun = false): Promise<boolean> {
  const docPath = join(repoRoot, 'docs', 'compound', 'README.md');
  if (!existsSync(docPath)) return false;

  const content = await readFile(docPath, 'utf-8');
  const updated = content.replace(/^(version: ")([^"]+)(")/m, `$1${newVersion}$3`);
  if (updated === content) return false;

  if (!dryRun) await writeFile(docPath, updated, 'utf-8');
  return true;
}

/** Run full upgrade flow. */
export async function runUpgrade(repoRoot: string, dryRun = false): Promise<UpgradeResult> {
  const isUpgrade = detectExistingInstall(repoRoot);

  if (!isUpgrade) {
    return {
      isUpgrade: false,
      strippedHeaders: 0,
      docVersionUpdated: false,
      message: 'No existing install detected. Nothing to upgrade.',
    };
  }

  const strippedHeaders = await stripGeneratedHeaders(repoRoot, dryRun);
  const docVersionUpdated = await upgradeDocVersion(repoRoot, VERSION, dryRun);

  const parts: string[] = [];
  if (strippedHeaders > 0) {
    parts.push(`Stripped headers from ${strippedHeaders} file(s)`);
  }
  if (docVersionUpdated) {
    parts.push('Updated doc version');
  }
  const message = parts.length > 0
    ? `Upgrade complete: ${parts.join(', ')}.`
    : 'Upgrade complete: no changes needed.';

  return { isUpgrade, strippedHeaders, docVersionUpdated, message };
}
