/**
 * Tests for the upgrade module.
 * Covers: detectExistingInstall, stripGeneratedHeaders, runUpgrade.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';

import {
  detectExistingInstall,
  stripGeneratedHeaders,
  upgradeDocVersion,
  runUpgrade,
} from './upgrade.js';

let tempDir: string;

beforeEach(async () => {
  tempDir = await mkdtemp(join(tmpdir(), 'upgrade-test-'));
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

describe('detectExistingInstall', () => {
  it('returns true when .claude/lessons/index.jsonl exists', async () => {
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    expect(detectExistingInstall(tempDir)).toBe(true);
  });

  it('returns false when .claude/lessons/index.jsonl does not exist', () => {
    expect(detectExistingInstall(tempDir)).toBe(false);
  });

  it('returns false when .claude/ exists but no lessons', async () => {
    await mkdir(join(tempDir, '.claude'), { recursive: true });

    expect(detectExistingInstall(tempDir)).toBe(false);
  });
});

describe('stripGeneratedHeaders', () => {
  it('strips header from files in commands/compound/', async () => {
    const dir = join(tempDir, '.claude', 'commands', 'compound');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'spec-dev.md'), '<!-- generated by compound-agent -->\ncontent here', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(1);
    const content = await readFile(join(dir, 'spec-dev.md'), 'utf-8');
    expect(content).toBe('content here');
  });

  it('strips header from files in skills/compound/', async () => {
    const dir = join(tempDir, '.claude', 'skills', 'compound', 'spec-dev');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'SKILL.md'), '<!-- generated by compound-agent -->\nskill content', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(1);
    const content = await readFile(join(dir, 'SKILL.md'), 'utf-8');
    expect(content).toBe('skill content');
  });

  it('strips header from files in agents/compound/', async () => {
    const dir = join(tempDir, '.claude', 'agents', 'compound');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'repo-analyst.md'), '<!-- generated by compound-agent -->\nagent content', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(1);
    const content = await readFile(join(dir, 'repo-analyst.md'), 'utf-8');
    expect(content).toBe('agent content');
  });

  it('does NOT strip from files without the header', async () => {
    const dir = join(tempDir, '.claude', 'commands', 'compound');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'custom.md'), 'no header here', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(0);
    const content = await readFile(join(dir, 'custom.md'), 'utf-8');
    expect(content).toBe('no header here');
  });

  it('handles multiple files across all three directories', async () => {
    const cmdDir = join(tempDir, '.claude', 'commands', 'compound');
    const skillDir = join(tempDir, '.claude', 'skills', 'compound', 'work');
    const agentDir = join(tempDir, '.claude', 'agents', 'compound');
    await mkdir(cmdDir, { recursive: true });
    await mkdir(skillDir, { recursive: true });
    await mkdir(agentDir, { recursive: true });

    await writeFile(join(cmdDir, 'a.md'), '<!-- generated by compound-agent -->\na', 'utf-8');
    await writeFile(join(cmdDir, 'b.md'), '<!-- generated by compound-agent -->\nb', 'utf-8');
    await writeFile(join(skillDir, 'SKILL.md'), '<!-- generated by compound-agent -->\nc', 'utf-8');
    await writeFile(join(agentDir, 'x.md'), '<!-- generated by compound-agent -->\nd', 'utf-8');
    await writeFile(join(agentDir, 'y.md'), 'no header', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(4);
  });

  it('returns 0 when no compound/ directories exist', async () => {
    const count = await stripGeneratedHeaders(tempDir);
    expect(count).toBe(0);
  });

  it('handles nested skill directories (skills/compound/agents/<name>/)', async () => {
    const dir = join(tempDir, '.claude', 'skills', 'compound', 'agents', 'test-writer');
    await mkdir(dir, { recursive: true });

    await writeFile(join(dir, 'SKILL.md'), '<!-- generated by compound-agent -->\nskill', 'utf-8');

    const count = await stripGeneratedHeaders(tempDir);

    expect(count).toBe(1);
    const content = await readFile(join(dir, 'SKILL.md'), 'utf-8');
    expect(content).toBe('skill');
  });
});

describe('runUpgrade', () => {
  it('returns isUpgrade: false when no existing install', async () => {
    const result = await runUpgrade(tempDir);

    expect(result.isUpgrade).toBe(false);
    expect(result.strippedHeaders).toBe(0);
    expect(result.docVersionUpdated).toBe(false);
    expect(result.message).toBeDefined();
  });

  it('returns isUpgrade: true when existing install detected', async () => {
    // Create existing install indicator
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    const result = await runUpgrade(tempDir);

    expect(result.isUpgrade).toBe(true);
  });

  it('orchestrates header stripping during upgrade', async () => {
    // Set up existing install
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    // Create files with headers
    const agentDir = join(tempDir, '.claude', 'agents', 'compound');
    await mkdir(agentDir, { recursive: true });
    await writeFile(join(agentDir, 'repo-analyst.md'), '<!-- generated by compound-agent -->\nagent', 'utf-8');

    const result = await runUpgrade(tempDir);

    expect(result.isUpgrade).toBe(true);
    expect(result.strippedHeaders).toBe(1);
    expect(result.message).toBeDefined();
  });

  it('provides a summary message', async () => {
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    const result = await runUpgrade(tempDir);

    expect(typeof result.message).toBe('string');
    expect(result.message.length).toBeGreaterThan(0);
  });

  it('updates doc version when README.md exists with old version', async () => {
    // Set up existing install
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    // Create doc with old version
    const docDir = join(tempDir, 'docs', 'compound');
    await mkdir(docDir, { recursive: true });
    await writeFile(
      join(docDir, 'README.md'),
      '---\nversion: "0.0.1"\n---\nContent here',
      'utf-8',
    );

    const result = await runUpgrade(tempDir);

    expect(result.docVersionUpdated).toBe(true);
    expect(result.message).toContain('Updated doc version');
  });

  it('returns docVersionUpdated: false when no doc file exists', async () => {
    // Set up existing install
    const lessonsDir = join(tempDir, '.claude', 'lessons');
    await mkdir(lessonsDir, { recursive: true });
    await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

    const result = await runUpgrade(tempDir);

    expect(result.docVersionUpdated).toBe(false);
  });
});

describe('dryRun mode', () => {
  describe('stripGeneratedHeaders with dryRun: true', () => {
    it('counts but does not write', async () => {
      const cmdDir = join(tempDir, '.claude', 'commands', 'compound');
      const agentDir = join(tempDir, '.claude', 'agents', 'compound');
      await mkdir(cmdDir, { recursive: true });
      await mkdir(agentDir, { recursive: true });

      const headerContent = '<!-- generated by compound-agent -->\ncontent';
      await writeFile(join(cmdDir, 'a.md'), headerContent, 'utf-8');
      await writeFile(join(agentDir, 'b.md'), headerContent, 'utf-8');

      const count = await stripGeneratedHeaders(tempDir, true);

      // Should report the count
      expect(count).toBe(2);
      // Files must still have the original header
      const contentA = await readFile(join(cmdDir, 'a.md'), 'utf-8');
      expect(contentA).toBe(headerContent);
      const contentB = await readFile(join(agentDir, 'b.md'), 'utf-8');
      expect(contentB).toBe(headerContent);
    });
  });

  describe('upgradeDocVersion with dryRun: true', () => {
    it('returns true but does not write', async () => {
      const docDir = join(tempDir, 'docs', 'compound');
      await mkdir(docDir, { recursive: true });
      const originalContent = '---\nversion: "0.0.1"\n---\nContent here';
      await writeFile(join(docDir, 'README.md'), originalContent, 'utf-8');

      const result = await upgradeDocVersion(tempDir, '9.9.9', true);

      expect(result).toBe(true);
      // File must still have the old version
      const content = await readFile(join(docDir, 'README.md'), 'utf-8');
      expect(content).toBe(originalContent);
    });
  });

  describe('runUpgrade with dryRun: true', () => {
    it('does not mutate filesystem', async () => {
      // Set up existing install
      const lessonsDir = join(tempDir, '.claude', 'lessons');
      await mkdir(lessonsDir, { recursive: true });
      await writeFile(join(lessonsDir, 'index.jsonl'), '', 'utf-8');

      // Create file with generated header
      const agentDir = join(tempDir, '.claude', 'agents', 'compound');
      await mkdir(agentDir, { recursive: true });
      const headerContent = '<!-- generated by compound-agent -->\nagent';
      await writeFile(join(agentDir, 'repo-analyst.md'), headerContent, 'utf-8');

      // Create doc with old version
      const docDir = join(tempDir, 'docs', 'compound');
      await mkdir(docDir, { recursive: true });
      const docContent = '---\nversion: "0.0.1"\n---\nContent here';
      await writeFile(join(docDir, 'README.md'), docContent, 'utf-8');

      const result = await runUpgrade(tempDir, true);

      // Should report all changes
      expect(result.isUpgrade).toBe(true);
      expect(result.strippedHeaders).toBe(1);
      expect(result.docVersionUpdated).toBe(true);

      // But nothing should have changed on disk
      const agentContent = await readFile(join(agentDir, 'repo-analyst.md'), 'utf-8');
      expect(agentContent).toBe(headerContent);
      const docOnDisk = await readFile(join(docDir, 'README.md'), 'utf-8');
      expect(docOnDisk).toBe(docContent);
    });
  });
});
