/**
 * Prebuild script: extracts last 3 version sections from CHANGELOG.md
 * and writes them to src/changelog-data.ts as a string constant.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const changelog = readFileSync(join(root, 'CHANGELOG.md'), 'utf-8');

// Extract ## [x.y.z] sections (skip [Unreleased])
const sectionRegex = /^## \[\d+\.\d+\.\d+\]/gm;
const matches: number[] = [];
let match: RegExpExecArray | null;
while ((match = sectionRegex.exec(changelog)) !== null) {
  matches.push(match.index);
}

// Take first 3 version sections
const sections = matches.slice(0, 3).map((start, i) => {
  const end = matches[i + 1] ?? changelog.length;
  return changelog.slice(start, end).trimEnd();
});

const content = sections.join('\n\n');
const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');

const output = `/**
 * Auto-generated changelog data — do not edit.
 * Generated by scripts/extract-changelog.ts
 */

export const CHANGELOG_RECENT: string = \`${escaped}\`;
`;

writeFileSync(join(root, 'src', 'changelog-data.ts'), output, 'utf-8');
console.log('Generated src/changelog-data.ts');
