/**
 * Prebuild script: extracts last 3 version sections from CHANGELOG.md
 * and writes them to src/changelog-data.ts as a string constant.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { extractSections, escapeForTemplateLiteral } from './changelog-utils.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const changelog = readFileSync(join(root, 'CHANGELOG.md'), 'utf-8');
const sections = extractSections(changelog);
const content = sections.join('\n\n');
const escaped = escapeForTemplateLiteral(content);

const output = `/**
 * Auto-generated changelog data — do not edit.
 * Generated by scripts/extract-changelog.ts
 */

export const CHANGELOG_RECENT: string = \`${escaped}\`;
`;

writeFileSync(join(root, 'src', 'changelog-data.ts'), output, 'utf-8');
console.log('Generated src/changelog-data.ts');
