/**
 * Auto-generated changelog data — do not edit.
 * Generated by scripts/extract-changelog.ts
 */

export const CHANGELOG_RECENT: string = `## [1.7.0] - 2026-03-08

### Added

- **Loop observability**: Generated loop script now writes \`.loop-status.json\` (real-time epic/attempt/status) and \`loop-execution.jsonl\` (append-only result log with per-epic duration and end-of-loop summary). Enables \`ca watch --status\` and post-mortem forensics.
- **ESLint rule \`no-solo-trivial-assertion\`**: Custom rule that warns when a test's only assertion is \`toBeDefined()\`, \`toBeTruthy()\`, \`toBeFalsy()\`, or \`toBeNull()\`. Registered but not yet enabled (requires cleanup of ~40 existing violations).

### Fixed

- **Loop 0-byte log resilience**: \`extract_text\` pipeline could produce 0-byte log files while the trace JSONL had valid content, causing the loop to falsely detect failure. New \`detect_marker()\` function checks the macro log first (anchored grep), then falls back to the trace JSONL (unanchored grep). Includes health check warning on extraction failure.
- **Search fallback when embeddings unavailable**: \`retrieveForPlan()\` no longer throws when the embedding model is missing or broken. Falls back to keyword-only search with a console warning.

### Changed

- **Anti-cargo-cult reviewer strengthened**: Added three new subtle anti-patterns to the reviewer agent: solo trivial assertions, substring-only \`toContain()\` checks, and keyword-presence tests. Each with bad/good examples.
- **Loop template extraction**: Bash script templates moved to \`loop-templates.ts\` to stay within lint limits.

## [1.6.5] - 2026-03-07

### Fixed

- **Loop script bash 3.2 syntax error**: macOS ships bash 3.2 which misparses \`case\` pattern \`)\` inside \`$(...)\` as closing the subshell. Added \`(\` prefix to case patterns for POSIX compliance. Added \`/bin/bash -n\` regression test.
- **Loop script \`--verbose\` flag**: \`--output-format=stream-json\` with \`-p\` requires \`--verbose\`, not \`--include-partial-messages\`.

## [1.6.4] - 2026-03-07

### Fixed

- **Embedding memory leak**: Every \`npx ca search\` spawned a process that loaded the ~150MB native embedding model. Without explicit cleanup, native threads kept processes alive as zombies. During heavy usage (Claude Code subagents), 32+ processes accumulated = 4.5GB leaked.
  - \`withEmbedding(fn)\` scoped wrapper guarantees cleanup via try/finally. All 9 command-layer consumers migrated from manual try/finally to this single API.
  - ESLint rule \`require-embedding-cleanup\` catches any file importing \`embedText\`/\`getEmbedding\` without a cleanup function. Scoped to \`src/commands/\` and \`src/setup/\`.
  - \`cli-app.ts\` backstop: top-level finally in \`runProgram()\` catches anything the above two miss.
- **\`embedText\` probe inside \`withEmbedding\` scope**: \`clean-lessons\` command was calling \`embedText\` outside of \`withEmbedding\`, leaking the model on every invocation.
- **Agentic skill report format**: Markdown table was missing \`|---|\` separator row, rendering as plain text in some renderers.
- **Agentic skill missing setup remediation**: 5 of 15 principles (P8, P12-P15) had no setup actions. Added concrete remediation guidance for each.
- **Agentic skill missing completion gate**: Other skills have phase gates; the agentic skill was missing one. Added Setup Completion Gate with verification steps.
- **Agentic skill stack-biased scoring**: Rubric was TypeScript-heavy. Added language-neutral scoring guidance (mypy, clippy, ruff equivalents).
- **Agentic skill \`$ARGUMENTS\` dead code**: Mode is set by the calling command (\`/compound:agentic-audit\` or \`/compound:agentic-setup\`), not parsed from \`$ARGUMENTS\`.
- **Docs template missing agentic commands**: \`SKILLS.md\` template now lists \`agentic-audit\` and \`agentic-setup\` in the command inventory.`;
