/**
 * Auto-generated changelog data — do not edit.
 * Generated by scripts/extract-changelog.ts
 */

export const CHANGELOG_RECENT: string = `## [1.3.7] - 2026-02-22

### Fixed

- **Flaky tests**: Hardened auto-sync, init, and stop-audit tests with proper subprocess timeouts, guard assertions, and path resolution fixes
- **Conditional expects**: Replaced silent-pass \`if (condition) { expect() }\` patterns with explicit \`it.runIf\`/\`it.skipIf\` in model.test.ts
- **Singleton test timing**: Replaced \`setTimeout(50)\` with deterministic microtask yield in nomic-singleton.test.ts

### Changed

- **Test pipeline**: Split vitest workspace into unit/integration/embedding projects; \`test:fast\` now runs in ~12s (was ~107s)
- **Export tests**: Consolidated 27 individual export-existence tests into 7 grouped assertions in index.test.ts

### Added

- \`pnpm test:unit\` and \`pnpm test:integration\` scripts for targeted test execution
- Integration tags on 8 CLI test files outside \`src/cli/\`

## [1.3.3] - 2026-02-21

### Changed

- **Banner audio**: Rewritten as vaporwave composition with PolyBLEP anti-aliased sawtooth synthesis, biquad filters, Schroeder reverb, and delay. E minor ambiguity resolves to E major at bloom, synced 300ms ahead of the visual climax (neural brain lighting up). Post-animation reverb tail holds 1.8s for natural dissolution.

## [1.3.2] - 2026-02-21

### Added

- **Banner audio**: Pure TypeScript WAV synthesis during the tendril animation. Cross-platform: \`afplay\` (macOS), \`aplay\` (Linux), PowerShell (Windows). Silently skips if player unavailable. Zero dependencies.
- **Test coverage**: 19 new tests for \`ca about\` command, changelog extraction/escaping, and \`--update\` doc migration path

### Fixed

- **\`setup --update\` doc migration**: \`--update\` now installs the 5 split docs before removing legacy \`HOW_TO_COMPOUND.md\`, preventing empty \`docs/compound/\`
- **Fresh checkout type-check**: \`src/changelog-data.ts\` tracked in git so \`tsc --noEmit\` passes without a prior build
- **Trailing status text**: Banner animation no longer leaves "al tendrils..." remnant from previous phase

### Changed

- **\`ca about\` command**: Renamed from \`ca version-show\` for brevity
- **Changelog extraction**: Core parsing/escaping logic extracted to \`scripts/changelog-utils.ts\` (shared between prebuild script and tests)
- **Narrowed \`.gitignore\`**: Setup-generated patterns scoped to \`compound/\` subdirectories to avoid hiding tracked TDD agent definitions`;
